// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package containerengine

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Work Request Log Entries in Oracle Cloud Infrastructure Container Engine service.
//
// Get the logs of a work request.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci/containerengine"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := containerengine.GetWorkRequestLogEntries(ctx, &containerengine.GetWorkRequestLogEntriesArgs{
// 			CompartmentId: _var.Compartment_id,
// 			WorkRequestId: oci_containerengine_work_request.Test_work_request.Id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetWorkRequestLogEntries(ctx *pulumi.Context, args *GetWorkRequestLogEntriesArgs, opts ...pulumi.InvokeOption) (*GetWorkRequestLogEntriesResult, error) {
	var rv GetWorkRequestLogEntriesResult
	err := ctx.Invoke("oci:containerengine/getWorkRequestLogEntries:getWorkRequestLogEntries", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getWorkRequestLogEntries.
type GetWorkRequestLogEntriesArgs struct {
	// The OCID of the compartment.
	CompartmentId string                           `pulumi:"compartmentId"`
	Filters       []GetWorkRequestLogEntriesFilter `pulumi:"filters"`
	// The OCID of the work request.
	WorkRequestId string `pulumi:"workRequestId"`
}

// A collection of values returned by getWorkRequestLogEntries.
type GetWorkRequestLogEntriesResult struct {
	CompartmentId string                           `pulumi:"compartmentId"`
	Filters       []GetWorkRequestLogEntriesFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id            string `pulumi:"id"`
	WorkRequestId string `pulumi:"workRequestId"`
	// The list of work_request_log_entries.
	WorkRequestLogEntries []GetWorkRequestLogEntriesWorkRequestLogEntry `pulumi:"workRequestLogEntries"`
}
