# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetNetworkLoadBalancerBackendSetsResult',
    'AwaitableGetNetworkLoadBalancerBackendSetsResult',
    'get_network_load_balancer_backend_sets',
]

@pulumi.output_type
class GetNetworkLoadBalancerBackendSetsResult:
    """
    A collection of values returned by GetNetworkLoadBalancerBackendSets.
    """
    def __init__(__self__, backend_set_collections=None, filters=None, id=None, network_load_balancer_id=None):
        if backend_set_collections and not isinstance(backend_set_collections, list):
            raise TypeError("Expected argument 'backend_set_collections' to be a list")
        pulumi.set(__self__, "backend_set_collections", backend_set_collections)
        if filters and not isinstance(filters, list):
            raise TypeError("Expected argument 'filters' to be a list")
        pulumi.set(__self__, "filters", filters)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if network_load_balancer_id and not isinstance(network_load_balancer_id, str):
            raise TypeError("Expected argument 'network_load_balancer_id' to be a str")
        pulumi.set(__self__, "network_load_balancer_id", network_load_balancer_id)

    @property
    @pulumi.getter(name="backendSetCollections")
    def backend_set_collections(self) -> Sequence['outputs.GetNetworkLoadBalancerBackendSetsBackendSetCollectionResult']:
        """
        The list of backend_set_collection.
        """
        return pulumi.get(self, "backend_set_collections")

    @property
    @pulumi.getter
    def filters(self) -> Optional[Sequence['outputs.GetNetworkLoadBalancerBackendSetsFilterResult']]:
        return pulumi.get(self, "filters")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="networkLoadBalancerId")
    def network_load_balancer_id(self) -> str:
        return pulumi.get(self, "network_load_balancer_id")


class AwaitableGetNetworkLoadBalancerBackendSetsResult(GetNetworkLoadBalancerBackendSetsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNetworkLoadBalancerBackendSetsResult(
            backend_set_collections=self.backend_set_collections,
            filters=self.filters,
            id=self.id,
            network_load_balancer_id=self.network_load_balancer_id)


def get_network_load_balancer_backend_sets(filters: Optional[Sequence[pulumi.InputType['GetNetworkLoadBalancerBackendSetsFilterArgs']]] = None,
                                           network_load_balancer_id: Optional[str] = None,
                                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNetworkLoadBalancerBackendSetsResult:
    """
    This data source provides the list of Backend Sets in Oracle Cloud Infrastructure Network Load Balancer service.

    Lists all backend sets associated with a given network load balancer.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_oci as oci

    test_backend_sets = oci.get_network_load_balancer_backend_sets(network_load_balancer_id=oci_network_load_balancer_network_load_balancer["test_network_load_balancer"]["id"])
    ```


    :param str network_load_balancer_id: The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the network load balancer to update.
    """
    __args__ = dict()
    __args__['filters'] = filters
    __args__['networkLoadBalancerId'] = network_load_balancer_id
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('oci:index/getNetworkLoadBalancerBackendSets:GetNetworkLoadBalancerBackendSets', __args__, opts=opts, typ=GetNetworkLoadBalancerBackendSetsResult).value

    return AwaitableGetNetworkLoadBalancerBackendSetsResult(
        backend_set_collections=__ret__.backend_set_collections,
        filters=__ret__.filters,
        id=__ret__.id,
        network_load_balancer_id=__ret__.network_load_balancer_id)
