// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetArtifactsContainerConfiguration
    {
        /// <summary>
        /// This data source provides details about a specific Container Configuration resource in Oracle Cloud Infrastructure Artifacts service.
        /// 
        /// Get container configuration.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testContainerConfiguration = Output.Create(Oci.GetArtifactsContainerConfiguration.InvokeAsync(new Oci.GetArtifactsContainerConfigurationArgs
        ///         {
        ///             CompartmentId = @var.Compartment_id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetArtifactsContainerConfigurationResult> InvokeAsync(GetArtifactsContainerConfigurationArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetArtifactsContainerConfigurationResult>("oci:index/getArtifactsContainerConfiguration:GetArtifactsContainerConfiguration", args ?? new GetArtifactsContainerConfigurationArgs(), options.WithVersion());
    }


    public sealed class GetArtifactsContainerConfigurationArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
        /// </summary>
        [Input("compartmentId", required: true)]
        public string CompartmentId { get; set; } = null!;

        public GetArtifactsContainerConfigurationArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetArtifactsContainerConfigurationResult
    {
        public readonly string CompartmentId;
        public readonly string Id;
        /// <summary>
        /// Whether to create a new container repository when a container is pushed to a new repository path. Repositories created in this way belong to the root compartment.
        /// </summary>
        public readonly bool IsRepositoryCreatedOnFirstPush;
        /// <summary>
        /// The tenancy namespace used in the container repository path.
        /// </summary>
        public readonly string Namespace;

        [OutputConstructor]
        private GetArtifactsContainerConfigurationResult(
            string compartmentId,

            string id,

            bool isRepositoryCreatedOnFirstPush,

            string @namespace)
        {
            CompartmentId = compartmentId;
            Id = id;
            IsRepositoryCreatedOnFirstPush = isRepositoryCreatedOnFirstPush;
            Namespace = @namespace;
        }
    }
}
