// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetCoreInternetGateways
    {
        /// <summary>
        /// This data source provides the list of Internet Gateways in Oracle Cloud Infrastructure Core service.
        /// 
        /// Lists the internet gateways in the specified VCN and the specified compartment.
        /// If the VCN ID is not provided, then the list includes the internet gateways from all VCNs in the specified compartment.
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testInternetGateways = Output.Create(Oci.GetCoreInternetGateways.InvokeAsync(new Oci.GetCoreInternetGatewaysArgs
        ///         {
        ///             CompartmentId = @var.Compartment_id,
        ///             DisplayName = @var.Internet_gateway_display_name,
        ///             State = @var.Internet_gateway_state,
        ///             VcnId = oci_core_vcn.Test_vcn.Id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetCoreInternetGatewaysResult> InvokeAsync(GetCoreInternetGatewaysArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetCoreInternetGatewaysResult>("oci:index/getCoreInternetGateways:GetCoreInternetGateways", args ?? new GetCoreInternetGatewaysArgs(), options.WithVersion());
    }


    public sealed class GetCoreInternetGatewaysArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
        /// </summary>
        [Input("compartmentId", required: true)]
        public string CompartmentId { get; set; } = null!;

        /// <summary>
        /// A filter to return only resources that match the given display name exactly.
        /// </summary>
        [Input("displayName")]
        public string? DisplayName { get; set; }

        [Input("filters")]
        private List<Inputs.GetCoreInternetGatewaysFilterArgs>? _filters;
        public List<Inputs.GetCoreInternetGatewaysFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetCoreInternetGatewaysFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// A filter to only return resources that match the given lifecycle state. The state value is case-insensitive.
        /// </summary>
        [Input("state")]
        public string? State { get; set; }

        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the VCN.
        /// </summary>
        [Input("vcnId")]
        public string? VcnId { get; set; }

        public GetCoreInternetGatewaysArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetCoreInternetGatewaysResult
    {
        /// <summary>
        /// The OCID of the compartment containing the internet gateway.
        /// </summary>
        public readonly string CompartmentId;
        /// <summary>
        /// A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.
        /// </summary>
        public readonly string? DisplayName;
        public readonly ImmutableArray<Outputs.GetCoreInternetGatewaysFilterResult> Filters;
        /// <summary>
        /// The list of gateways.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCoreInternetGatewaysGatewayResult> Gateways;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The internet gateway's current state.
        /// </summary>
        public readonly string? State;
        /// <summary>
        /// The OCID of the VCN the internet gateway belongs to.
        /// </summary>
        public readonly string? VcnId;

        [OutputConstructor]
        private GetCoreInternetGatewaysResult(
            string compartmentId,

            string? displayName,

            ImmutableArray<Outputs.GetCoreInternetGatewaysFilterResult> filters,

            ImmutableArray<Outputs.GetCoreInternetGatewaysGatewayResult> gateways,

            string id,

            string? state,

            string? vcnId)
        {
            CompartmentId = compartmentId;
            DisplayName = displayName;
            Filters = filters;
            Gateways = gateways;
            Id = id;
            State = state;
            VcnId = vcnId;
        }
    }
}
