// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetDatabaseVmClusterPatchHistoryEntry
    {
        /// <summary>
        /// This data source provides details about a specific Vm Cluster Patch History Entry resource in Oracle Cloud Infrastructure Database service.
        /// 
        /// Gets the patch history details for the specified patch history entry.
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testVmClusterPatchHistoryEntry = Output.Create(Oci.GetDatabaseVmClusterPatchHistoryEntry.InvokeAsync(new Oci.GetDatabaseVmClusterPatchHistoryEntryArgs
        ///         {
        ///             PatchHistoryEntryId = oci_database_patch_history_entry.Test_patch_history_entry.Id,
        ///             VmClusterId = oci_database_vm_cluster.Test_vm_cluster.Id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDatabaseVmClusterPatchHistoryEntryResult> InvokeAsync(GetDatabaseVmClusterPatchHistoryEntryArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDatabaseVmClusterPatchHistoryEntryResult>("oci:index/getDatabaseVmClusterPatchHistoryEntry:GetDatabaseVmClusterPatchHistoryEntry", args ?? new GetDatabaseVmClusterPatchHistoryEntryArgs(), options.WithVersion());
    }


    public sealed class GetDatabaseVmClusterPatchHistoryEntryArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the patch history entry.
        /// </summary>
        [Input("patchHistoryEntryId", required: true)]
        public string PatchHistoryEntryId { get; set; } = null!;

        /// <summary>
        /// The VM cluster [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
        /// </summary>
        [Input("vmClusterId", required: true)]
        public string VmClusterId { get; set; } = null!;

        public GetDatabaseVmClusterPatchHistoryEntryArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDatabaseVmClusterPatchHistoryEntryResult
    {
        /// <summary>
        /// The action being performed or was completed.
        /// </summary>
        public readonly string Action;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A descriptive text associated with the lifecycleState. Typically contains additional displayable text.
        /// </summary>
        public readonly string LifecycleDetails;
        public readonly string PatchHistoryEntryId;
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the patch.
        /// </summary>
        public readonly string PatchId;
        /// <summary>
        /// The current state of the action.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// The date and time when the patch action completed
        /// </summary>
        public readonly string TimeEnded;
        /// <summary>
        /// The date and time when the patch action started.
        /// </summary>
        public readonly string TimeStarted;
        public readonly string VmClusterId;

        [OutputConstructor]
        private GetDatabaseVmClusterPatchHistoryEntryResult(
            string action,

            string id,

            string lifecycleDetails,

            string patchHistoryEntryId,

            string patchId,

            string state,

            string timeEnded,

            string timeStarted,

            string vmClusterId)
        {
            Action = action;
            Id = id;
            LifecycleDetails = lifecycleDetails;
            PatchHistoryEntryId = patchHistoryEntryId;
            PatchId = patchId;
            State = state;
            TimeEnded = timeEnded;
            TimeStarted = timeStarted;
            VmClusterId = vmClusterId;
        }
    }
}
