// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetDatabaseVmClusterNetworks
    {
        /// <summary>
        /// This data source provides the list of Vm Cluster Networks in Oracle Cloud Infrastructure Database service.
        /// 
        /// Gets a list of the VM cluster networks in the specified compartment. Applies to Exadata Cloud@Customer instances only.
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testVmClusterNetworks = Output.Create(Oci.GetDatabaseVmClusterNetworks.InvokeAsync(new Oci.GetDatabaseVmClusterNetworksArgs
        ///         {
        ///             CompartmentId = @var.Compartment_id,
        ///             ExadataInfrastructureId = oci_database_exadata_infrastructure.Test_exadata_infrastructure.Id,
        ///             DisplayName = @var.Vm_cluster_network_display_name,
        ///             State = @var.Vm_cluster_network_state,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDatabaseVmClusterNetworksResult> InvokeAsync(GetDatabaseVmClusterNetworksArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDatabaseVmClusterNetworksResult>("oci:index/getDatabaseVmClusterNetworks:GetDatabaseVmClusterNetworks", args ?? new GetDatabaseVmClusterNetworksArgs(), options.WithVersion());
    }


    public sealed class GetDatabaseVmClusterNetworksArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The compartment [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
        /// </summary>
        [Input("compartmentId", required: true)]
        public string CompartmentId { get; set; } = null!;

        /// <summary>
        /// A filter to return only resources that match the entire display name given. The match is not case sensitive.
        /// </summary>
        [Input("displayName")]
        public string? DisplayName { get; set; }

        /// <summary>
        /// The Exadata infrastructure [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
        /// </summary>
        [Input("exadataInfrastructureId", required: true)]
        public string ExadataInfrastructureId { get; set; } = null!;

        [Input("filters")]
        private List<Inputs.GetDatabaseVmClusterNetworksFilterArgs>? _filters;
        public List<Inputs.GetDatabaseVmClusterNetworksFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetDatabaseVmClusterNetworksFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// A filter to return only resources that match the given lifecycle state exactly.
        /// </summary>
        [Input("state")]
        public string? State { get; set; }

        public GetDatabaseVmClusterNetworksArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDatabaseVmClusterNetworksResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
        /// </summary>
        public readonly string CompartmentId;
        /// <summary>
        /// The user-friendly name for the VM cluster network. The name does not need to be unique.
        /// </summary>
        public readonly string? DisplayName;
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Exadata infrastructure.
        /// </summary>
        public readonly string ExadataInfrastructureId;
        public readonly ImmutableArray<Outputs.GetDatabaseVmClusterNetworksFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The current state of the VM cluster network.
        /// </summary>
        public readonly string? State;
        /// <summary>
        /// The list of vm_cluster_networks.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDatabaseVmClusterNetworksVmClusterNetworkResult> VmClusterNetworks;

        [OutputConstructor]
        private GetDatabaseVmClusterNetworksResult(
            string compartmentId,

            string? displayName,

            string exadataInfrastructureId,

            ImmutableArray<Outputs.GetDatabaseVmClusterNetworksFilterResult> filters,

            string id,

            string? state,

            ImmutableArray<Outputs.GetDatabaseVmClusterNetworksVmClusterNetworkResult> vmClusterNetworks)
        {
            CompartmentId = compartmentId;
            DisplayName = displayName;
            ExadataInfrastructureId = exadataInfrastructureId;
            Filters = filters;
            Id = id;
            State = state;
            VmClusterNetworks = vmClusterNetworks;
        }
    }
}
