// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetDatabaseKeyStores
    {
        /// <summary>
        /// This data source provides the list of Key Stores in Oracle Cloud Infrastructure Database service.
        /// 
        /// Gets a list of key stores in the specified compartment.
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testKeyStores = Output.Create(Oci.GetDatabaseKeyStores.InvokeAsync(new Oci.GetDatabaseKeyStoresArgs
        ///         {
        ///             CompartmentId = @var.Compartment_id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDatabaseKeyStoresResult> InvokeAsync(GetDatabaseKeyStoresArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDatabaseKeyStoresResult>("oci:index/getDatabaseKeyStores:GetDatabaseKeyStores", args ?? new GetDatabaseKeyStoresArgs(), options.WithVersion());
    }


    public sealed class GetDatabaseKeyStoresArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The compartment [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
        /// </summary>
        [Input("compartmentId", required: true)]
        public string CompartmentId { get; set; } = null!;

        [Input("filters")]
        private List<Inputs.GetDatabaseKeyStoresFilterArgs>? _filters;
        public List<Inputs.GetDatabaseKeyStoresFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetDatabaseKeyStoresFilterArgs>());
            set => _filters = value;
        }

        public GetDatabaseKeyStoresArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDatabaseKeyStoresResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
        /// </summary>
        public readonly string CompartmentId;
        public readonly ImmutableArray<Outputs.GetDatabaseKeyStoresFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of key_stores.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDatabaseKeyStoresKeyStoreResult> KeyStores;

        [OutputConstructor]
        private GetDatabaseKeyStoresResult(
            string compartmentId,

            ImmutableArray<Outputs.GetDatabaseKeyStoresFilterResult> filters,

            string id,

            ImmutableArray<Outputs.GetDatabaseKeyStoresKeyStoreResult> keyStores)
        {
            CompartmentId = compartmentId;
            Filters = filters;
            Id = id;
            KeyStores = keyStores;
        }
    }
}
