// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetLoadBalancerBackendSets
    {
        /// <summary>
        /// This data source provides the list of Backend Sets in Oracle Cloud Infrastructure Load Balancer service.
        /// 
        /// Lists all backend sets associated with a given load balancer.
        /// 
        /// ## Supported Aliases
        /// 
        /// * `oci_load_balancer_backendsets`
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testBackendSets = Output.Create(Oci.GetLoadBalancerBackendSets.InvokeAsync(new Oci.GetLoadBalancerBackendSetsArgs
        ///         {
        ///             LoadBalancerId = oci_load_balancer_load_balancer.Test_load_balancer.Id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetLoadBalancerBackendSetsResult> InvokeAsync(GetLoadBalancerBackendSetsArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetLoadBalancerBackendSetsResult>("oci:index/getLoadBalancerBackendSets:GetLoadBalancerBackendSets", args ?? new GetLoadBalancerBackendSetsArgs(), options.WithVersion());
    }


    public sealed class GetLoadBalancerBackendSetsArgs : Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetLoadBalancerBackendSetsFilterArgs>? _filters;
        public List<Inputs.GetLoadBalancerBackendSetsFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetLoadBalancerBackendSetsFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the load balancer associated with the backend sets to retrieve.
        /// </summary>
        [Input("loadBalancerId", required: true)]
        public string LoadBalancerId { get; set; } = null!;

        public GetLoadBalancerBackendSetsArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetLoadBalancerBackendSetsResult
    {
        /// <summary>
        /// The list of backendsets.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetLoadBalancerBackendSetsBackendsetResult> Backendsets;
        public readonly ImmutableArray<Outputs.GetLoadBalancerBackendSetsFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string LoadBalancerId;

        [OutputConstructor]
        private GetLoadBalancerBackendSetsResult(
            ImmutableArray<Outputs.GetLoadBalancerBackendSetsBackendsetResult> backendsets,

            ImmutableArray<Outputs.GetLoadBalancerBackendSetsFilterResult> filters,

            string id,

            string loadBalancerId)
        {
            Backendsets = backendsets;
            Filters = filters;
            Id = id;
            LoadBalancerId = loadBalancerId;
        }
    }
}
