// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetManagementAgentManagementAgentImages
    {
        /// <summary>
        /// This data source provides the list of Management Agent Images in Oracle Cloud Infrastructure Management Agent service.
        /// 
        /// Get supported agent image information
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testManagementAgentImages = Output.Create(Oci.GetManagementAgentManagementAgentImages.InvokeAsync(new Oci.GetManagementAgentManagementAgentImagesArgs
        ///         {
        ///             CompartmentId = @var.Compartment_id,
        ///             Name = @var.Management_agent_image_name,
        ///             State = @var.Management_agent_image_state,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetManagementAgentManagementAgentImagesResult> InvokeAsync(GetManagementAgentManagementAgentImagesArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetManagementAgentManagementAgentImagesResult>("oci:index/getManagementAgentManagementAgentImages:GetManagementAgentManagementAgentImages", args ?? new GetManagementAgentManagementAgentImagesArgs(), options.WithVersion());
    }


    public sealed class GetManagementAgentManagementAgentImagesArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the compartment from which the Management Agents to be listed.
        /// </summary>
        [Input("compartmentId", required: true)]
        public string CompartmentId { get; set; } = null!;

        [Input("filters")]
        private List<Inputs.GetManagementAgentManagementAgentImagesFilterArgs>? _filters;
        public List<Inputs.GetManagementAgentManagementAgentImagesFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetManagementAgentManagementAgentImagesFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// A filter to return only resources that match the entire platform name given.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Filter to return only Management Agents in the particular lifecycle state.
        /// </summary>
        [Input("state")]
        public string? State { get; set; }

        public GetManagementAgentManagementAgentImagesArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetManagementAgentManagementAgentImagesResult
    {
        public readonly string CompartmentId;
        public readonly ImmutableArray<Outputs.GetManagementAgentManagementAgentImagesFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of management_agent_images.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetManagementAgentManagementAgentImagesManagementAgentImageResult> ManagementAgentImages;
        public readonly string? Name;
        /// <summary>
        /// The current state of Management Agent Image
        /// </summary>
        public readonly string? State;

        [OutputConstructor]
        private GetManagementAgentManagementAgentImagesResult(
            string compartmentId,

            ImmutableArray<Outputs.GetManagementAgentManagementAgentImagesFilterResult> filters,

            string id,

            ImmutableArray<Outputs.GetManagementAgentManagementAgentImagesManagementAgentImageResult> managementAgentImages,

            string? name,

            string? state)
        {
            CompartmentId = compartmentId;
            Filters = filters;
            Id = id;
            ManagementAgentImages = managementAgentImages;
            Name = name;
            State = state;
        }
    }
}
