// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci
{
    public static class GetWaasCustomProtectionRules
    {
        /// <summary>
        /// This data source provides the list of Custom Protection Rules in Oracle Cloud Infrastructure Web Application Acceleration and Security service.
        /// 
        /// Gets a list of custom protection rules for the specified Web Application Firewall.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var testCustomProtectionRules = Output.Create(Oci.GetWaasCustomProtectionRules.InvokeAsync(new Oci.GetWaasCustomProtectionRulesArgs
        ///         {
        ///             CompartmentId = @var.Compartment_id,
        ///             DisplayNames = @var.Custom_protection_rule_display_names,
        ///             Ids = @var.Custom_protection_rule_ids,
        ///             States = @var.Custom_protection_rule_states,
        ///             TimeCreatedGreaterThanOrEqualTo = @var.Custom_protection_rule_time_created_greater_than_or_equal_to,
        ///             TimeCreatedLessThan = @var.Custom_protection_rule_time_created_less_than,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetWaasCustomProtectionRulesResult> InvokeAsync(GetWaasCustomProtectionRulesArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetWaasCustomProtectionRulesResult>("oci:index/getWaasCustomProtectionRules:GetWaasCustomProtectionRules", args ?? new GetWaasCustomProtectionRulesArgs(), options.WithVersion());
    }


    public sealed class GetWaasCustomProtectionRulesArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment. This number is generated when the compartment is created.
        /// </summary>
        [Input("compartmentId", required: true)]
        public string CompartmentId { get; set; } = null!;

        [Input("displayNames")]
        private List<string>? _displayNames;

        /// <summary>
        /// Filter custom protection rules using a list of display names.
        /// </summary>
        public List<string> DisplayNames
        {
            get => _displayNames ?? (_displayNames = new List<string>());
            set => _displayNames = value;
        }

        [Input("filters")]
        private List<Inputs.GetWaasCustomProtectionRulesFilterArgs>? _filters;
        public List<Inputs.GetWaasCustomProtectionRulesFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetWaasCustomProtectionRulesFilterArgs>());
            set => _filters = value;
        }

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// Filter custom protection rules using a list of custom protection rule OCIDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        [Input("states")]
        private List<string>? _states;

        /// <summary>
        /// Filter Custom Protection rules using a list of lifecycle states.
        /// </summary>
        public List<string> States
        {
            get => _states ?? (_states = new List<string>());
            set => _states = value;
        }

        /// <summary>
        /// A filter that matches Custom Protection rules created on or after the specified date-time.
        /// </summary>
        [Input("timeCreatedGreaterThanOrEqualTo")]
        public string? TimeCreatedGreaterThanOrEqualTo { get; set; }

        /// <summary>
        /// A filter that matches custom protection rules created before the specified date-time.
        /// </summary>
        [Input("timeCreatedLessThan")]
        public string? TimeCreatedLessThan { get; set; }

        public GetWaasCustomProtectionRulesArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetWaasCustomProtectionRulesResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the custom protection rule's compartment.
        /// </summary>
        public readonly string CompartmentId;
        /// <summary>
        /// The list of custom_protection_rules.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetWaasCustomProtectionRulesCustomProtectionRuleResult> CustomProtectionRules;
        public readonly ImmutableArray<string> DisplayNames;
        public readonly ImmutableArray<Outputs.GetWaasCustomProtectionRulesFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly ImmutableArray<string> States;
        public readonly string? TimeCreatedGreaterThanOrEqualTo;
        public readonly string? TimeCreatedLessThan;

        [OutputConstructor]
        private GetWaasCustomProtectionRulesResult(
            string compartmentId,

            ImmutableArray<Outputs.GetWaasCustomProtectionRulesCustomProtectionRuleResult> customProtectionRules,

            ImmutableArray<string> displayNames,

            ImmutableArray<Outputs.GetWaasCustomProtectionRulesFilterResult> filters,

            string id,

            ImmutableArray<string> ids,

            ImmutableArray<string> states,

            string? timeCreatedGreaterThanOrEqualTo,

            string? timeCreatedLessThan)
        {
            CompartmentId = compartmentId;
            CustomProtectionRules = customProtectionRules;
            DisplayNames = displayNames;
            Filters = filters;
            Id = id;
            Ids = ids;
            States = states;
            TimeCreatedGreaterThanOrEqualTo = timeCreatedGreaterThanOrEqualTo;
            TimeCreatedLessThan = timeCreatedLessThan;
        }
    }
}
