// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package cloudguard

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource provides the Cloud Guard Configuration resource in Oracle Cloud Infrastructure Cloud Guard service.
//
// Enable/Disable Cloud Guard. The reporting region cannot be updated once created.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci/cloudguard"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := cloudguard.NewCloudGuardConfiguration(ctx, "testCloudGuardConfiguration", &cloudguard.CloudGuardConfigurationArgs{
// 			CompartmentId:       pulumi.Any(_var.Compartment_id),
// 			ReportingRegion:     pulumi.Any(_var.Cloud_guard_configuration_reporting_region),
// 			Status:              pulumi.Any(_var.Cloud_guard_configuration_status),
// 			SelfManageResources: pulumi.Any(_var.Cloud_guard_configuration_self_manage_resources),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// Import is not supported for this resource.
type CloudGuardConfiguration struct {
	pulumi.CustomResourceState

	// (Updatable) The ID of the compartment in which to list resources.
	CompartmentId pulumi.StringOutput `pulumi:"compartmentId"`
	// (Updatable) The reporting region value
	ReportingRegion pulumi.StringOutput `pulumi:"reportingRegion"`
	// (Updatable) Identifies if Oracle managed resources will be created by customers. If no value is specified false is the default.
	SelfManageResources pulumi.BoolOutput `pulumi:"selfManageResources"`
	// (Updatable) Status of Cloud Guard Tenant
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewCloudGuardConfiguration registers a new resource with the given unique name, arguments, and options.
func NewCloudGuardConfiguration(ctx *pulumi.Context,
	name string, args *CloudGuardConfigurationArgs, opts ...pulumi.ResourceOption) (*CloudGuardConfiguration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CompartmentId == nil {
		return nil, errors.New("invalid value for required argument 'CompartmentId'")
	}
	if args.ReportingRegion == nil {
		return nil, errors.New("invalid value for required argument 'ReportingRegion'")
	}
	if args.Status == nil {
		return nil, errors.New("invalid value for required argument 'Status'")
	}
	var resource CloudGuardConfiguration
	err := ctx.RegisterResource("oci:cloudguard/cloudGuardConfiguration:CloudGuardConfiguration", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudGuardConfiguration gets an existing CloudGuardConfiguration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudGuardConfiguration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudGuardConfigurationState, opts ...pulumi.ResourceOption) (*CloudGuardConfiguration, error) {
	var resource CloudGuardConfiguration
	err := ctx.ReadResource("oci:cloudguard/cloudGuardConfiguration:CloudGuardConfiguration", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudGuardConfiguration resources.
type cloudGuardConfigurationState struct {
	// (Updatable) The ID of the compartment in which to list resources.
	CompartmentId *string `pulumi:"compartmentId"`
	// (Updatable) The reporting region value
	ReportingRegion *string `pulumi:"reportingRegion"`
	// (Updatable) Identifies if Oracle managed resources will be created by customers. If no value is specified false is the default.
	SelfManageResources *bool `pulumi:"selfManageResources"`
	// (Updatable) Status of Cloud Guard Tenant
	Status *string `pulumi:"status"`
}

type CloudGuardConfigurationState struct {
	// (Updatable) The ID of the compartment in which to list resources.
	CompartmentId pulumi.StringPtrInput
	// (Updatable) The reporting region value
	ReportingRegion pulumi.StringPtrInput
	// (Updatable) Identifies if Oracle managed resources will be created by customers. If no value is specified false is the default.
	SelfManageResources pulumi.BoolPtrInput
	// (Updatable) Status of Cloud Guard Tenant
	Status pulumi.StringPtrInput
}

func (CloudGuardConfigurationState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudGuardConfigurationState)(nil)).Elem()
}

type cloudGuardConfigurationArgs struct {
	// (Updatable) The ID of the compartment in which to list resources.
	CompartmentId string `pulumi:"compartmentId"`
	// (Updatable) The reporting region value
	ReportingRegion string `pulumi:"reportingRegion"`
	// (Updatable) Identifies if Oracle managed resources will be created by customers. If no value is specified false is the default.
	SelfManageResources *bool `pulumi:"selfManageResources"`
	// (Updatable) Status of Cloud Guard Tenant
	Status string `pulumi:"status"`
}

// The set of arguments for constructing a CloudGuardConfiguration resource.
type CloudGuardConfigurationArgs struct {
	// (Updatable) The ID of the compartment in which to list resources.
	CompartmentId pulumi.StringInput
	// (Updatable) The reporting region value
	ReportingRegion pulumi.StringInput
	// (Updatable) Identifies if Oracle managed resources will be created by customers. If no value is specified false is the default.
	SelfManageResources pulumi.BoolPtrInput
	// (Updatable) Status of Cloud Guard Tenant
	Status pulumi.StringInput
}

func (CloudGuardConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudGuardConfigurationArgs)(nil)).Elem()
}

type CloudGuardConfigurationInput interface {
	pulumi.Input

	ToCloudGuardConfigurationOutput() CloudGuardConfigurationOutput
	ToCloudGuardConfigurationOutputWithContext(ctx context.Context) CloudGuardConfigurationOutput
}

func (*CloudGuardConfiguration) ElementType() reflect.Type {
	return reflect.TypeOf((*CloudGuardConfiguration)(nil))
}

func (i *CloudGuardConfiguration) ToCloudGuardConfigurationOutput() CloudGuardConfigurationOutput {
	return i.ToCloudGuardConfigurationOutputWithContext(context.Background())
}

func (i *CloudGuardConfiguration) ToCloudGuardConfigurationOutputWithContext(ctx context.Context) CloudGuardConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudGuardConfigurationOutput)
}

func (i *CloudGuardConfiguration) ToCloudGuardConfigurationPtrOutput() CloudGuardConfigurationPtrOutput {
	return i.ToCloudGuardConfigurationPtrOutputWithContext(context.Background())
}

func (i *CloudGuardConfiguration) ToCloudGuardConfigurationPtrOutputWithContext(ctx context.Context) CloudGuardConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudGuardConfigurationPtrOutput)
}

type CloudGuardConfigurationPtrInput interface {
	pulumi.Input

	ToCloudGuardConfigurationPtrOutput() CloudGuardConfigurationPtrOutput
	ToCloudGuardConfigurationPtrOutputWithContext(ctx context.Context) CloudGuardConfigurationPtrOutput
}

type cloudGuardConfigurationPtrType CloudGuardConfigurationArgs

func (*cloudGuardConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudGuardConfiguration)(nil))
}

func (i *cloudGuardConfigurationPtrType) ToCloudGuardConfigurationPtrOutput() CloudGuardConfigurationPtrOutput {
	return i.ToCloudGuardConfigurationPtrOutputWithContext(context.Background())
}

func (i *cloudGuardConfigurationPtrType) ToCloudGuardConfigurationPtrOutputWithContext(ctx context.Context) CloudGuardConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudGuardConfigurationPtrOutput)
}

// CloudGuardConfigurationArrayInput is an input type that accepts CloudGuardConfigurationArray and CloudGuardConfigurationArrayOutput values.
// You can construct a concrete instance of `CloudGuardConfigurationArrayInput` via:
//
//          CloudGuardConfigurationArray{ CloudGuardConfigurationArgs{...} }
type CloudGuardConfigurationArrayInput interface {
	pulumi.Input

	ToCloudGuardConfigurationArrayOutput() CloudGuardConfigurationArrayOutput
	ToCloudGuardConfigurationArrayOutputWithContext(context.Context) CloudGuardConfigurationArrayOutput
}

type CloudGuardConfigurationArray []CloudGuardConfigurationInput

func (CloudGuardConfigurationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudGuardConfiguration)(nil)).Elem()
}

func (i CloudGuardConfigurationArray) ToCloudGuardConfigurationArrayOutput() CloudGuardConfigurationArrayOutput {
	return i.ToCloudGuardConfigurationArrayOutputWithContext(context.Background())
}

func (i CloudGuardConfigurationArray) ToCloudGuardConfigurationArrayOutputWithContext(ctx context.Context) CloudGuardConfigurationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudGuardConfigurationArrayOutput)
}

// CloudGuardConfigurationMapInput is an input type that accepts CloudGuardConfigurationMap and CloudGuardConfigurationMapOutput values.
// You can construct a concrete instance of `CloudGuardConfigurationMapInput` via:
//
//          CloudGuardConfigurationMap{ "key": CloudGuardConfigurationArgs{...} }
type CloudGuardConfigurationMapInput interface {
	pulumi.Input

	ToCloudGuardConfigurationMapOutput() CloudGuardConfigurationMapOutput
	ToCloudGuardConfigurationMapOutputWithContext(context.Context) CloudGuardConfigurationMapOutput
}

type CloudGuardConfigurationMap map[string]CloudGuardConfigurationInput

func (CloudGuardConfigurationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudGuardConfiguration)(nil)).Elem()
}

func (i CloudGuardConfigurationMap) ToCloudGuardConfigurationMapOutput() CloudGuardConfigurationMapOutput {
	return i.ToCloudGuardConfigurationMapOutputWithContext(context.Background())
}

func (i CloudGuardConfigurationMap) ToCloudGuardConfigurationMapOutputWithContext(ctx context.Context) CloudGuardConfigurationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudGuardConfigurationMapOutput)
}

type CloudGuardConfigurationOutput struct {
	*pulumi.OutputState
}

func (CloudGuardConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CloudGuardConfiguration)(nil))
}

func (o CloudGuardConfigurationOutput) ToCloudGuardConfigurationOutput() CloudGuardConfigurationOutput {
	return o
}

func (o CloudGuardConfigurationOutput) ToCloudGuardConfigurationOutputWithContext(ctx context.Context) CloudGuardConfigurationOutput {
	return o
}

func (o CloudGuardConfigurationOutput) ToCloudGuardConfigurationPtrOutput() CloudGuardConfigurationPtrOutput {
	return o.ToCloudGuardConfigurationPtrOutputWithContext(context.Background())
}

func (o CloudGuardConfigurationOutput) ToCloudGuardConfigurationPtrOutputWithContext(ctx context.Context) CloudGuardConfigurationPtrOutput {
	return o.ApplyT(func(v CloudGuardConfiguration) *CloudGuardConfiguration {
		return &v
	}).(CloudGuardConfigurationPtrOutput)
}

type CloudGuardConfigurationPtrOutput struct {
	*pulumi.OutputState
}

func (CloudGuardConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudGuardConfiguration)(nil))
}

func (o CloudGuardConfigurationPtrOutput) ToCloudGuardConfigurationPtrOutput() CloudGuardConfigurationPtrOutput {
	return o
}

func (o CloudGuardConfigurationPtrOutput) ToCloudGuardConfigurationPtrOutputWithContext(ctx context.Context) CloudGuardConfigurationPtrOutput {
	return o
}

type CloudGuardConfigurationArrayOutput struct{ *pulumi.OutputState }

func (CloudGuardConfigurationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]CloudGuardConfiguration)(nil))
}

func (o CloudGuardConfigurationArrayOutput) ToCloudGuardConfigurationArrayOutput() CloudGuardConfigurationArrayOutput {
	return o
}

func (o CloudGuardConfigurationArrayOutput) ToCloudGuardConfigurationArrayOutputWithContext(ctx context.Context) CloudGuardConfigurationArrayOutput {
	return o
}

func (o CloudGuardConfigurationArrayOutput) Index(i pulumi.IntInput) CloudGuardConfigurationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) CloudGuardConfiguration {
		return vs[0].([]CloudGuardConfiguration)[vs[1].(int)]
	}).(CloudGuardConfigurationOutput)
}

type CloudGuardConfigurationMapOutput struct{ *pulumi.OutputState }

func (CloudGuardConfigurationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]CloudGuardConfiguration)(nil))
}

func (o CloudGuardConfigurationMapOutput) ToCloudGuardConfigurationMapOutput() CloudGuardConfigurationMapOutput {
	return o
}

func (o CloudGuardConfigurationMapOutput) ToCloudGuardConfigurationMapOutputWithContext(ctx context.Context) CloudGuardConfigurationMapOutput {
	return o
}

func (o CloudGuardConfigurationMapOutput) MapIndex(k pulumi.StringInput) CloudGuardConfigurationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) CloudGuardConfiguration {
		return vs[0].(map[string]CloudGuardConfiguration)[vs[1].(string)]
	}).(CloudGuardConfigurationOutput)
}

func init() {
	pulumi.RegisterOutputType(CloudGuardConfigurationOutput{})
	pulumi.RegisterOutputType(CloudGuardConfigurationPtrOutput{})
	pulumi.RegisterOutputType(CloudGuardConfigurationArrayOutput{})
	pulumi.RegisterOutputType(CloudGuardConfigurationMapOutput{})
}
