// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource provides the Target Database resource in Oracle Cloud Infrastructure Data Safe service.
//
// Registers the specified database with Data Safe and creates a Data Safe target database in the Data Safe Console.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := oci.NewDataSafeTargetDatabase(ctx, "testTargetDatabase", &oci.DataSafeTargetDatabaseArgs{
// 			CompartmentId: pulumi.Any(_var.Compartment_id),
// 			DatabaseDetails: &DataSafeTargetDatabaseDatabaseDetailsArgs{
// 				DatabaseType:         pulumi.Any(_var.Target_database_database_details_database_type),
// 				InfrastructureType:   pulumi.Any(_var.Target_database_database_details_infrastructure_type),
// 				AutonomousDatabaseId: pulumi.Any(oci_database_autonomous_database.Test_autonomous_database.Id),
// 				DbSystemId:           pulumi.Any(oci_database_db_system.Test_db_system.Id),
// 				InstanceId:           pulumi.Any(oci_core_instance.Test_instance.Id),
// 				IpAddresses:          pulumi.Any(_var.Target_database_database_details_ip_addresses),
// 				ListenerPort:         pulumi.Any(_var.Target_database_database_details_listener_port),
// 				ServiceName:          pulumi.Any(oci_core_service.Test_service.Name),
// 				VmClusterId:          pulumi.Any(oci_database_vm_cluster.Test_vm_cluster.Id),
// 			},
// 			ConnectionOption: &DataSafeTargetDatabaseConnectionOptionArgs{
// 				ConnectionType:            pulumi.Any(_var.Target_database_connection_option_connection_type),
// 				DatasafePrivateEndpointId: pulumi.Any(oci_dataflow_private_endpoint.Test_private_endpoint.Id),
// 				OnPremConnectorId:         pulumi.Any(oci_data_safe_on_prem_connector.Test_on_prem_connector.Id),
// 			},
// 			Credentials: &DataSafeTargetDatabaseCredentialsArgs{
// 				Password: pulumi.Any(_var.Target_database_credentials_password),
// 				UserName: pulumi.Any(oci_identity_user.Test_user.Name),
// 			},
// 			DefinedTags: pulumi.AnyMap{
// 				"Operations.CostCenter": pulumi.Any("42"),
// 			},
// 			Description: pulumi.Any(_var.Target_database_description),
// 			DisplayName: pulumi.Any(_var.Target_database_display_name),
// 			FreeformTags: pulumi.AnyMap{
// 				"Department": pulumi.Any("Finance"),
// 			},
// 			TlsConfig: &DataSafeTargetDatabaseTlsConfigArgs{
// 				Status:               pulumi.Any(_var.Target_database_tls_config_status),
// 				CertificateStoreType: pulumi.Any(_var.Target_database_tls_config_certificate_store_type),
// 				KeyStoreContent:      pulumi.Any(_var.Target_database_tls_config_key_store_content),
// 				StorePassword:        pulumi.Any(_var.Target_database_tls_config_store_password),
// 				TrustStoreContent:    pulumi.Any(_var.Target_database_tls_config_trust_store_content),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// TargetDatabases can be imported using the `id`, e.g.
//
// ```sh
//  $ pulumi import oci:index/dataSafeTargetDatabase:DataSafeTargetDatabase test_target_database "id"
// ```
type DataSafeTargetDatabase struct {
	pulumi.CustomResourceState

	// (Updatable) The OCID of the compartment in which to create the Data Safe target database.
	CompartmentId pulumi.StringOutput `pulumi:"compartmentId"`
	// (Updatable) Types of connection supported by Data Safe.
	ConnectionOption DataSafeTargetDatabaseConnectionOptionOutput `pulumi:"connectionOption"`
	// (Updatable) The database credentials required for Data Safe to connect to the database.
	Credentials DataSafeTargetDatabaseCredentialsOutput `pulumi:"credentials"`
	// (Updatable) Details of the database for the registration in Data Safe. To choose applicable database type and infrastructure type refer to  https://confluence.oci.oraclecorp.com/display/DATASAFE/Target+V2+Design
	DatabaseDetails DataSafeTargetDatabaseDatabaseDetailsOutput `pulumi:"databaseDetails"`
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Operations.CostCenter": "42"}`
	DefinedTags pulumi.MapOutput `pulumi:"definedTags"`
	// (Updatable) The description of the target database in Data Safe.
	Description pulumi.StringOutput `pulumi:"description"`
	// (Updatable) The display name of the target database in Data Safe. The name is modifiable and does not need to be unique.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Department": "Finance"}`
	FreeformTags pulumi.MapOutput `pulumi:"freeformTags"`
	// Details about the current state of the target database in Data Safe.
	LifecycleDetails pulumi.StringOutput `pulumi:"lifecycleDetails"`
	// The current state of the target database in Data Safe.
	State pulumi.StringOutput `pulumi:"state"`
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: `{"orcl-cloud.free-tier-retained": "true"}`
	SystemTags pulumi.MapOutput `pulumi:"systemTags"`
	// The date and time the database was registered in Data Safe and created as a target database in Data Safe.
	TimeCreated pulumi.StringOutput `pulumi:"timeCreated"`
	// The date and time of the target database update in Data Safe.
	TimeUpdated pulumi.StringOutput `pulumi:"timeUpdated"`
	// (Updatable) The details required to establish a TLS enabled connection.
	TlsConfig DataSafeTargetDatabaseTlsConfigOutput `pulumi:"tlsConfig"`
}

// NewDataSafeTargetDatabase registers a new resource with the given unique name, arguments, and options.
func NewDataSafeTargetDatabase(ctx *pulumi.Context,
	name string, args *DataSafeTargetDatabaseArgs, opts ...pulumi.ResourceOption) (*DataSafeTargetDatabase, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CompartmentId == nil {
		return nil, errors.New("invalid value for required argument 'CompartmentId'")
	}
	if args.DatabaseDetails == nil {
		return nil, errors.New("invalid value for required argument 'DatabaseDetails'")
	}
	var resource DataSafeTargetDatabase
	err := ctx.RegisterResource("oci:index/dataSafeTargetDatabase:DataSafeTargetDatabase", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDataSafeTargetDatabase gets an existing DataSafeTargetDatabase resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDataSafeTargetDatabase(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DataSafeTargetDatabaseState, opts ...pulumi.ResourceOption) (*DataSafeTargetDatabase, error) {
	var resource DataSafeTargetDatabase
	err := ctx.ReadResource("oci:index/dataSafeTargetDatabase:DataSafeTargetDatabase", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DataSafeTargetDatabase resources.
type dataSafeTargetDatabaseState struct {
	// (Updatable) The OCID of the compartment in which to create the Data Safe target database.
	CompartmentId *string `pulumi:"compartmentId"`
	// (Updatable) Types of connection supported by Data Safe.
	ConnectionOption *DataSafeTargetDatabaseConnectionOption `pulumi:"connectionOption"`
	// (Updatable) The database credentials required for Data Safe to connect to the database.
	Credentials *DataSafeTargetDatabaseCredentials `pulumi:"credentials"`
	// (Updatable) Details of the database for the registration in Data Safe. To choose applicable database type and infrastructure type refer to  https://confluence.oci.oraclecorp.com/display/DATASAFE/Target+V2+Design
	DatabaseDetails *DataSafeTargetDatabaseDatabaseDetails `pulumi:"databaseDetails"`
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Operations.CostCenter": "42"}`
	DefinedTags map[string]interface{} `pulumi:"definedTags"`
	// (Updatable) The description of the target database in Data Safe.
	Description *string `pulumi:"description"`
	// (Updatable) The display name of the target database in Data Safe. The name is modifiable and does not need to be unique.
	DisplayName *string `pulumi:"displayName"`
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Department": "Finance"}`
	FreeformTags map[string]interface{} `pulumi:"freeformTags"`
	// Details about the current state of the target database in Data Safe.
	LifecycleDetails *string `pulumi:"lifecycleDetails"`
	// The current state of the target database in Data Safe.
	State *string `pulumi:"state"`
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: `{"orcl-cloud.free-tier-retained": "true"}`
	SystemTags map[string]interface{} `pulumi:"systemTags"`
	// The date and time the database was registered in Data Safe and created as a target database in Data Safe.
	TimeCreated *string `pulumi:"timeCreated"`
	// The date and time of the target database update in Data Safe.
	TimeUpdated *string `pulumi:"timeUpdated"`
	// (Updatable) The details required to establish a TLS enabled connection.
	TlsConfig *DataSafeTargetDatabaseTlsConfig `pulumi:"tlsConfig"`
}

type DataSafeTargetDatabaseState struct {
	// (Updatable) The OCID of the compartment in which to create the Data Safe target database.
	CompartmentId pulumi.StringPtrInput
	// (Updatable) Types of connection supported by Data Safe.
	ConnectionOption DataSafeTargetDatabaseConnectionOptionPtrInput
	// (Updatable) The database credentials required for Data Safe to connect to the database.
	Credentials DataSafeTargetDatabaseCredentialsPtrInput
	// (Updatable) Details of the database for the registration in Data Safe. To choose applicable database type and infrastructure type refer to  https://confluence.oci.oraclecorp.com/display/DATASAFE/Target+V2+Design
	DatabaseDetails DataSafeTargetDatabaseDatabaseDetailsPtrInput
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Operations.CostCenter": "42"}`
	DefinedTags pulumi.MapInput
	// (Updatable) The description of the target database in Data Safe.
	Description pulumi.StringPtrInput
	// (Updatable) The display name of the target database in Data Safe. The name is modifiable and does not need to be unique.
	DisplayName pulumi.StringPtrInput
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Department": "Finance"}`
	FreeformTags pulumi.MapInput
	// Details about the current state of the target database in Data Safe.
	LifecycleDetails pulumi.StringPtrInput
	// The current state of the target database in Data Safe.
	State pulumi.StringPtrInput
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: `{"orcl-cloud.free-tier-retained": "true"}`
	SystemTags pulumi.MapInput
	// The date and time the database was registered in Data Safe and created as a target database in Data Safe.
	TimeCreated pulumi.StringPtrInput
	// The date and time of the target database update in Data Safe.
	TimeUpdated pulumi.StringPtrInput
	// (Updatable) The details required to establish a TLS enabled connection.
	TlsConfig DataSafeTargetDatabaseTlsConfigPtrInput
}

func (DataSafeTargetDatabaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*dataSafeTargetDatabaseState)(nil)).Elem()
}

type dataSafeTargetDatabaseArgs struct {
	// (Updatable) The OCID of the compartment in which to create the Data Safe target database.
	CompartmentId string `pulumi:"compartmentId"`
	// (Updatable) Types of connection supported by Data Safe.
	ConnectionOption *DataSafeTargetDatabaseConnectionOption `pulumi:"connectionOption"`
	// (Updatable) The database credentials required for Data Safe to connect to the database.
	Credentials *DataSafeTargetDatabaseCredentials `pulumi:"credentials"`
	// (Updatable) Details of the database for the registration in Data Safe. To choose applicable database type and infrastructure type refer to  https://confluence.oci.oraclecorp.com/display/DATASAFE/Target+V2+Design
	DatabaseDetails DataSafeTargetDatabaseDatabaseDetails `pulumi:"databaseDetails"`
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Operations.CostCenter": "42"}`
	DefinedTags map[string]interface{} `pulumi:"definedTags"`
	// (Updatable) The description of the target database in Data Safe.
	Description *string `pulumi:"description"`
	// (Updatable) The display name of the target database in Data Safe. The name is modifiable and does not need to be unique.
	DisplayName *string `pulumi:"displayName"`
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Department": "Finance"}`
	FreeformTags map[string]interface{} `pulumi:"freeformTags"`
	// (Updatable) The details required to establish a TLS enabled connection.
	TlsConfig *DataSafeTargetDatabaseTlsConfig `pulumi:"tlsConfig"`
}

// The set of arguments for constructing a DataSafeTargetDatabase resource.
type DataSafeTargetDatabaseArgs struct {
	// (Updatable) The OCID of the compartment in which to create the Data Safe target database.
	CompartmentId pulumi.StringInput
	// (Updatable) Types of connection supported by Data Safe.
	ConnectionOption DataSafeTargetDatabaseConnectionOptionPtrInput
	// (Updatable) The database credentials required for Data Safe to connect to the database.
	Credentials DataSafeTargetDatabaseCredentialsPtrInput
	// (Updatable) Details of the database for the registration in Data Safe. To choose applicable database type and infrastructure type refer to  https://confluence.oci.oraclecorp.com/display/DATASAFE/Target+V2+Design
	DatabaseDetails DataSafeTargetDatabaseDatabaseDetailsInput
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Operations.CostCenter": "42"}`
	DefinedTags pulumi.MapInput
	// (Updatable) The description of the target database in Data Safe.
	Description pulumi.StringPtrInput
	// (Updatable) The display name of the target database in Data Safe. The name is modifiable and does not need to be unique.
	DisplayName pulumi.StringPtrInput
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)  Example: `{"Department": "Finance"}`
	FreeformTags pulumi.MapInput
	// (Updatable) The details required to establish a TLS enabled connection.
	TlsConfig DataSafeTargetDatabaseTlsConfigPtrInput
}

func (DataSafeTargetDatabaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dataSafeTargetDatabaseArgs)(nil)).Elem()
}

type DataSafeTargetDatabaseInput interface {
	pulumi.Input

	ToDataSafeTargetDatabaseOutput() DataSafeTargetDatabaseOutput
	ToDataSafeTargetDatabaseOutputWithContext(ctx context.Context) DataSafeTargetDatabaseOutput
}

func (*DataSafeTargetDatabase) ElementType() reflect.Type {
	return reflect.TypeOf((*DataSafeTargetDatabase)(nil))
}

func (i *DataSafeTargetDatabase) ToDataSafeTargetDatabaseOutput() DataSafeTargetDatabaseOutput {
	return i.ToDataSafeTargetDatabaseOutputWithContext(context.Background())
}

func (i *DataSafeTargetDatabase) ToDataSafeTargetDatabaseOutputWithContext(ctx context.Context) DataSafeTargetDatabaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataSafeTargetDatabaseOutput)
}

func (i *DataSafeTargetDatabase) ToDataSafeTargetDatabasePtrOutput() DataSafeTargetDatabasePtrOutput {
	return i.ToDataSafeTargetDatabasePtrOutputWithContext(context.Background())
}

func (i *DataSafeTargetDatabase) ToDataSafeTargetDatabasePtrOutputWithContext(ctx context.Context) DataSafeTargetDatabasePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataSafeTargetDatabasePtrOutput)
}

type DataSafeTargetDatabasePtrInput interface {
	pulumi.Input

	ToDataSafeTargetDatabasePtrOutput() DataSafeTargetDatabasePtrOutput
	ToDataSafeTargetDatabasePtrOutputWithContext(ctx context.Context) DataSafeTargetDatabasePtrOutput
}

type dataSafeTargetDatabasePtrType DataSafeTargetDatabaseArgs

func (*dataSafeTargetDatabasePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DataSafeTargetDatabase)(nil))
}

func (i *dataSafeTargetDatabasePtrType) ToDataSafeTargetDatabasePtrOutput() DataSafeTargetDatabasePtrOutput {
	return i.ToDataSafeTargetDatabasePtrOutputWithContext(context.Background())
}

func (i *dataSafeTargetDatabasePtrType) ToDataSafeTargetDatabasePtrOutputWithContext(ctx context.Context) DataSafeTargetDatabasePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataSafeTargetDatabasePtrOutput)
}

// DataSafeTargetDatabaseArrayInput is an input type that accepts DataSafeTargetDatabaseArray and DataSafeTargetDatabaseArrayOutput values.
// You can construct a concrete instance of `DataSafeTargetDatabaseArrayInput` via:
//
//          DataSafeTargetDatabaseArray{ DataSafeTargetDatabaseArgs{...} }
type DataSafeTargetDatabaseArrayInput interface {
	pulumi.Input

	ToDataSafeTargetDatabaseArrayOutput() DataSafeTargetDatabaseArrayOutput
	ToDataSafeTargetDatabaseArrayOutputWithContext(context.Context) DataSafeTargetDatabaseArrayOutput
}

type DataSafeTargetDatabaseArray []DataSafeTargetDatabaseInput

func (DataSafeTargetDatabaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DataSafeTargetDatabase)(nil)).Elem()
}

func (i DataSafeTargetDatabaseArray) ToDataSafeTargetDatabaseArrayOutput() DataSafeTargetDatabaseArrayOutput {
	return i.ToDataSafeTargetDatabaseArrayOutputWithContext(context.Background())
}

func (i DataSafeTargetDatabaseArray) ToDataSafeTargetDatabaseArrayOutputWithContext(ctx context.Context) DataSafeTargetDatabaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataSafeTargetDatabaseArrayOutput)
}

// DataSafeTargetDatabaseMapInput is an input type that accepts DataSafeTargetDatabaseMap and DataSafeTargetDatabaseMapOutput values.
// You can construct a concrete instance of `DataSafeTargetDatabaseMapInput` via:
//
//          DataSafeTargetDatabaseMap{ "key": DataSafeTargetDatabaseArgs{...} }
type DataSafeTargetDatabaseMapInput interface {
	pulumi.Input

	ToDataSafeTargetDatabaseMapOutput() DataSafeTargetDatabaseMapOutput
	ToDataSafeTargetDatabaseMapOutputWithContext(context.Context) DataSafeTargetDatabaseMapOutput
}

type DataSafeTargetDatabaseMap map[string]DataSafeTargetDatabaseInput

func (DataSafeTargetDatabaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DataSafeTargetDatabase)(nil)).Elem()
}

func (i DataSafeTargetDatabaseMap) ToDataSafeTargetDatabaseMapOutput() DataSafeTargetDatabaseMapOutput {
	return i.ToDataSafeTargetDatabaseMapOutputWithContext(context.Background())
}

func (i DataSafeTargetDatabaseMap) ToDataSafeTargetDatabaseMapOutputWithContext(ctx context.Context) DataSafeTargetDatabaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataSafeTargetDatabaseMapOutput)
}

type DataSafeTargetDatabaseOutput struct {
	*pulumi.OutputState
}

func (DataSafeTargetDatabaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataSafeTargetDatabase)(nil))
}

func (o DataSafeTargetDatabaseOutput) ToDataSafeTargetDatabaseOutput() DataSafeTargetDatabaseOutput {
	return o
}

func (o DataSafeTargetDatabaseOutput) ToDataSafeTargetDatabaseOutputWithContext(ctx context.Context) DataSafeTargetDatabaseOutput {
	return o
}

func (o DataSafeTargetDatabaseOutput) ToDataSafeTargetDatabasePtrOutput() DataSafeTargetDatabasePtrOutput {
	return o.ToDataSafeTargetDatabasePtrOutputWithContext(context.Background())
}

func (o DataSafeTargetDatabaseOutput) ToDataSafeTargetDatabasePtrOutputWithContext(ctx context.Context) DataSafeTargetDatabasePtrOutput {
	return o.ApplyT(func(v DataSafeTargetDatabase) *DataSafeTargetDatabase {
		return &v
	}).(DataSafeTargetDatabasePtrOutput)
}

type DataSafeTargetDatabasePtrOutput struct {
	*pulumi.OutputState
}

func (DataSafeTargetDatabasePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DataSafeTargetDatabase)(nil))
}

func (o DataSafeTargetDatabasePtrOutput) ToDataSafeTargetDatabasePtrOutput() DataSafeTargetDatabasePtrOutput {
	return o
}

func (o DataSafeTargetDatabasePtrOutput) ToDataSafeTargetDatabasePtrOutputWithContext(ctx context.Context) DataSafeTargetDatabasePtrOutput {
	return o
}

type DataSafeTargetDatabaseArrayOutput struct{ *pulumi.OutputState }

func (DataSafeTargetDatabaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataSafeTargetDatabase)(nil))
}

func (o DataSafeTargetDatabaseArrayOutput) ToDataSafeTargetDatabaseArrayOutput() DataSafeTargetDatabaseArrayOutput {
	return o
}

func (o DataSafeTargetDatabaseArrayOutput) ToDataSafeTargetDatabaseArrayOutputWithContext(ctx context.Context) DataSafeTargetDatabaseArrayOutput {
	return o
}

func (o DataSafeTargetDatabaseArrayOutput) Index(i pulumi.IntInput) DataSafeTargetDatabaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DataSafeTargetDatabase {
		return vs[0].([]DataSafeTargetDatabase)[vs[1].(int)]
	}).(DataSafeTargetDatabaseOutput)
}

type DataSafeTargetDatabaseMapOutput struct{ *pulumi.OutputState }

func (DataSafeTargetDatabaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]DataSafeTargetDatabase)(nil))
}

func (o DataSafeTargetDatabaseMapOutput) ToDataSafeTargetDatabaseMapOutput() DataSafeTargetDatabaseMapOutput {
	return o
}

func (o DataSafeTargetDatabaseMapOutput) ToDataSafeTargetDatabaseMapOutputWithContext(ctx context.Context) DataSafeTargetDatabaseMapOutput {
	return o
}

func (o DataSafeTargetDatabaseMapOutput) MapIndex(k pulumi.StringInput) DataSafeTargetDatabaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) DataSafeTargetDatabase {
		return vs[0].(map[string]DataSafeTargetDatabase)[vs[1].(string)]
	}).(DataSafeTargetDatabaseOutput)
}

func init() {
	pulumi.RegisterOutputType(DataSafeTargetDatabaseOutput{})
	pulumi.RegisterOutputType(DataSafeTargetDatabasePtrOutput{})
	pulumi.RegisterOutputType(DataSafeTargetDatabaseArrayOutput{})
	pulumi.RegisterOutputType(DataSafeTargetDatabaseMapOutput{})
}
