// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource provides the Managed Databases Change Database Parameter resource in Oracle Cloud Infrastructure Database Management service.
//
// Changes database parameter values. There are two kinds of database
// parameters:
//
// - Dynamic parameters: They can be changed for the current Oracle
//   Database instance. The changes take effect immediately.
// - Static parameters: They cannot be changed for the current instance.
//   You must change these parameters and then restart the database before
//   changes take effect.
//
// **Note:** If the instance is started using a text initialization
// parameter file, the parameter changes are applicable only for the
// current instance. You must update them manually to be passed to
// a future instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := oci.NewDatabaseManagementManagedDatabasesChangeDatabaseParameter(ctx, "testManagedDatabasesChangeDatabaseParameter", &oci.DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs{
// 			Credentials: &DatabaseManagementManagedDatabasesChangeDatabaseParameterCredentialsArgs{
// 				Password: pulumi.Any(_var.Managed_databases_change_database_parameter_credentials_password),
// 				Role:     pulumi.Any(_var.Managed_databases_change_database_parameter_credentials_role),
// 				UserName: pulumi.Any(oci_identity_user.Test_user.Name),
// 			},
// 			ManagedDatabaseId: pulumi.Any(oci_database_management_managed_database.Test_managed_database.Id),
// 			Parameters: DatabaseManagementManagedDatabasesChangeDatabaseParameterParameterArray{
// 				&DatabaseManagementManagedDatabasesChangeDatabaseParameterParameterArgs{
// 					Name:          pulumi.Any(_var.Managed_databases_change_database_parameter_parameters_name),
// 					Value:         pulumi.Any(_var.Managed_databases_change_database_parameter_parameters_value),
// 					UpdateComment: pulumi.Any(_var.Managed_databases_change_database_parameter_parameters_update_comment),
// 				},
// 			},
// 			Scope: pulumi.Any(_var.Managed_databases_change_database_parameter_scope),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// Import is not supported for this resource.
type DatabaseManagementManagedDatabasesChangeDatabaseParameter struct {
	pulumi.CustomResourceState

	// The database credentials used to perform management activity.
	Credentials DatabaseManagementManagedDatabasesChangeDatabaseParameterCredentialsOutput `pulumi:"credentials"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database.
	ManagedDatabaseId pulumi.StringOutput `pulumi:"managedDatabaseId"`
	// A list of database parameters and their values.
	Parameters DatabaseManagementManagedDatabasesChangeDatabaseParameterParameterArrayOutput `pulumi:"parameters"`
	// The clause used to specify when the parameter change takes effect.
	Scope pulumi.StringOutput `pulumi:"scope"`
}

// NewDatabaseManagementManagedDatabasesChangeDatabaseParameter registers a new resource with the given unique name, arguments, and options.
func NewDatabaseManagementManagedDatabasesChangeDatabaseParameter(ctx *pulumi.Context,
	name string, args *DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs, opts ...pulumi.ResourceOption) (*DatabaseManagementManagedDatabasesChangeDatabaseParameter, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Credentials == nil {
		return nil, errors.New("invalid value for required argument 'Credentials'")
	}
	if args.ManagedDatabaseId == nil {
		return nil, errors.New("invalid value for required argument 'ManagedDatabaseId'")
	}
	if args.Parameters == nil {
		return nil, errors.New("invalid value for required argument 'Parameters'")
	}
	if args.Scope == nil {
		return nil, errors.New("invalid value for required argument 'Scope'")
	}
	var resource DatabaseManagementManagedDatabasesChangeDatabaseParameter
	err := ctx.RegisterResource("oci:index/databaseManagementManagedDatabasesChangeDatabaseParameter:DatabaseManagementManagedDatabasesChangeDatabaseParameter", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabaseManagementManagedDatabasesChangeDatabaseParameter gets an existing DatabaseManagementManagedDatabasesChangeDatabaseParameter resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabaseManagementManagedDatabasesChangeDatabaseParameter(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseManagementManagedDatabasesChangeDatabaseParameterState, opts ...pulumi.ResourceOption) (*DatabaseManagementManagedDatabasesChangeDatabaseParameter, error) {
	var resource DatabaseManagementManagedDatabasesChangeDatabaseParameter
	err := ctx.ReadResource("oci:index/databaseManagementManagedDatabasesChangeDatabaseParameter:DatabaseManagementManagedDatabasesChangeDatabaseParameter", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DatabaseManagementManagedDatabasesChangeDatabaseParameter resources.
type databaseManagementManagedDatabasesChangeDatabaseParameterState struct {
	// The database credentials used to perform management activity.
	Credentials *DatabaseManagementManagedDatabasesChangeDatabaseParameterCredentials `pulumi:"credentials"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database.
	ManagedDatabaseId *string `pulumi:"managedDatabaseId"`
	// A list of database parameters and their values.
	Parameters []DatabaseManagementManagedDatabasesChangeDatabaseParameterParameter `pulumi:"parameters"`
	// The clause used to specify when the parameter change takes effect.
	Scope *string `pulumi:"scope"`
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterState struct {
	// The database credentials used to perform management activity.
	Credentials DatabaseManagementManagedDatabasesChangeDatabaseParameterCredentialsPtrInput
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database.
	ManagedDatabaseId pulumi.StringPtrInput
	// A list of database parameters and their values.
	Parameters DatabaseManagementManagedDatabasesChangeDatabaseParameterParameterArrayInput
	// The clause used to specify when the parameter change takes effect.
	Scope pulumi.StringPtrInput
}

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseManagementManagedDatabasesChangeDatabaseParameterState)(nil)).Elem()
}

type databaseManagementManagedDatabasesChangeDatabaseParameterArgs struct {
	// The database credentials used to perform management activity.
	Credentials DatabaseManagementManagedDatabasesChangeDatabaseParameterCredentials `pulumi:"credentials"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database.
	ManagedDatabaseId string `pulumi:"managedDatabaseId"`
	// A list of database parameters and their values.
	Parameters []DatabaseManagementManagedDatabasesChangeDatabaseParameterParameter `pulumi:"parameters"`
	// The clause used to specify when the parameter change takes effect.
	Scope string `pulumi:"scope"`
}

// The set of arguments for constructing a DatabaseManagementManagedDatabasesChangeDatabaseParameter resource.
type DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs struct {
	// The database credentials used to perform management activity.
	Credentials DatabaseManagementManagedDatabasesChangeDatabaseParameterCredentialsInput
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database.
	ManagedDatabaseId pulumi.StringInput
	// A list of database parameters and their values.
	Parameters DatabaseManagementManagedDatabasesChangeDatabaseParameterParameterArrayInput
	// The clause used to specify when the parameter change takes effect.
	Scope pulumi.StringInput
}

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseManagementManagedDatabasesChangeDatabaseParameterArgs)(nil)).Elem()
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterInput interface {
	pulumi.Input

	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput
	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput
}

func (*DatabaseManagementManagedDatabasesChangeDatabaseParameter) ElementType() reflect.Type {
	return reflect.TypeOf((*DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil))
}

func (i *DatabaseManagementManagedDatabasesChangeDatabaseParameter) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput {
	return i.ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutputWithContext(context.Background())
}

func (i *DatabaseManagementManagedDatabasesChangeDatabaseParameter) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput)
}

func (i *DatabaseManagementManagedDatabasesChangeDatabaseParameter) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return i.ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(context.Background())
}

func (i *DatabaseManagementManagedDatabasesChangeDatabaseParameter) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput)
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrInput interface {
	pulumi.Input

	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput
	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput
}

type databaseManagementManagedDatabasesChangeDatabaseParameterPtrType DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs

func (*databaseManagementManagedDatabasesChangeDatabaseParameterPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil))
}

func (i *databaseManagementManagedDatabasesChangeDatabaseParameterPtrType) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return i.ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(context.Background())
}

func (i *databaseManagementManagedDatabasesChangeDatabaseParameterPtrType) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput)
}

// DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayInput is an input type that accepts DatabaseManagementManagedDatabasesChangeDatabaseParameterArray and DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput values.
// You can construct a concrete instance of `DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayInput` via:
//
//          DatabaseManagementManagedDatabasesChangeDatabaseParameterArray{ DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs{...} }
type DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayInput interface {
	pulumi.Input

	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput
	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutputWithContext(context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterArray []DatabaseManagementManagedDatabasesChangeDatabaseParameterInput

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil)).Elem()
}

func (i DatabaseManagementManagedDatabasesChangeDatabaseParameterArray) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput {
	return i.ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutputWithContext(context.Background())
}

func (i DatabaseManagementManagedDatabasesChangeDatabaseParameterArray) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput)
}

// DatabaseManagementManagedDatabasesChangeDatabaseParameterMapInput is an input type that accepts DatabaseManagementManagedDatabasesChangeDatabaseParameterMap and DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput values.
// You can construct a concrete instance of `DatabaseManagementManagedDatabasesChangeDatabaseParameterMapInput` via:
//
//          DatabaseManagementManagedDatabasesChangeDatabaseParameterMap{ "key": DatabaseManagementManagedDatabasesChangeDatabaseParameterArgs{...} }
type DatabaseManagementManagedDatabasesChangeDatabaseParameterMapInput interface {
	pulumi.Input

	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput
	ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutputWithContext(context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterMap map[string]DatabaseManagementManagedDatabasesChangeDatabaseParameterInput

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil)).Elem()
}

func (i DatabaseManagementManagedDatabasesChangeDatabaseParameterMap) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput {
	return i.ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutputWithContext(context.Background())
}

func (i DatabaseManagementManagedDatabasesChangeDatabaseParameterMap) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput)
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput struct {
	*pulumi.OutputState
}

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil))
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return o.ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(context.Background())
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return o.ApplyT(func(v DatabaseManagementManagedDatabasesChangeDatabaseParameter) *DatabaseManagementManagedDatabasesChangeDatabaseParameter {
		return &v
	}).(DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput)
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput struct {
	*pulumi.OutputState
}

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil))
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput {
	return o
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput struct{ *pulumi.OutputState }

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil))
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput) Index(i pulumi.IntInput) DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DatabaseManagementManagedDatabasesChangeDatabaseParameter {
		return vs[0].([]DatabaseManagementManagedDatabasesChangeDatabaseParameter)[vs[1].(int)]
	}).(DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput)
}

type DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput struct{ *pulumi.OutputState }

func (DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]DatabaseManagementManagedDatabasesChangeDatabaseParameter)(nil))
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput() DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput) ToDatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutputWithContext(ctx context.Context) DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput {
	return o
}

func (o DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput) MapIndex(k pulumi.StringInput) DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) DatabaseManagementManagedDatabasesChangeDatabaseParameter {
		return vs[0].(map[string]DatabaseManagementManagedDatabasesChangeDatabaseParameter)[vs[1].(string)]
	}).(DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput)
}

func init() {
	pulumi.RegisterOutputType(DatabaseManagementManagedDatabasesChangeDatabaseParameterOutput{})
	pulumi.RegisterOutputType(DatabaseManagementManagedDatabasesChangeDatabaseParameterPtrOutput{})
	pulumi.RegisterOutputType(DatabaseManagementManagedDatabasesChangeDatabaseParameterArrayOutput{})
	pulumi.RegisterOutputType(DatabaseManagementManagedDatabasesChangeDatabaseParameterMapOutput{})
}
