// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Blockchain Platforms in Oracle Cloud Infrastructure Blockchain service.
//
// Returns a list Blockchain Platform Instances in a compartment
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := _var.Blockchain_platform_display_name
// 		opt1 := _var.Blockchain_platform_state
// 		_, err := oci.GetBlockchainBlockchainPlatforms(ctx, &GetBlockchainBlockchainPlatformsArgs{
// 			CompartmentId: _var.Compartment_id,
// 			DisplayName:   &opt0,
// 			State:         &opt1,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetBlockchainBlockchainPlatforms(ctx *pulumi.Context, args *GetBlockchainBlockchainPlatformsArgs, opts ...pulumi.InvokeOption) (*GetBlockchainBlockchainPlatformsResult, error) {
	var rv GetBlockchainBlockchainPlatformsResult
	err := ctx.Invoke("oci:index/getBlockchainBlockchainPlatforms:GetBlockchainBlockchainPlatforms", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetBlockchainBlockchainPlatforms.
type GetBlockchainBlockchainPlatformsArgs struct {
	// The ID of the compartment in which to list resources.
	CompartmentId string `pulumi:"compartmentId"`
	// A user-friendly name. Does not have to be unique, and it's changeable. Example: `My new resource`
	DisplayName *string                                  `pulumi:"displayName"`
	Filters     []GetBlockchainBlockchainPlatformsFilter `pulumi:"filters"`
	// A filter to only return resources that match the given lifecycle state. The state value is case-insensitive.
	State *string `pulumi:"state"`
}

// A collection of values returned by GetBlockchainBlockchainPlatforms.
type GetBlockchainBlockchainPlatformsResult struct {
	// The list of blockchain_platform_collection.
	BlockchainPlatformCollections []GetBlockchainBlockchainPlatformsBlockchainPlatformCollection `pulumi:"blockchainPlatformCollections"`
	// Compartment Identifier
	CompartmentId string `pulumi:"compartmentId"`
	// Platform Instance Display name, can be renamed
	DisplayName *string                                  `pulumi:"displayName"`
	Filters     []GetBlockchainBlockchainPlatformsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The current state of the Platform Instance.
	State *string `pulumi:"state"`
}
