// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Compute Capacity Reservations in Oracle Cloud Infrastructure Core service.
//
// Lists the compute capacity reservations that match the specified criteria and compartment.
//
// You can limit the list by specifying a compute capacity reservation display name
// (the list will include all the identically-named compute capacity reservations in the compartment).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := _var.Compute_capacity_reservation_availability_domain
// 		opt1 := _var.Compute_capacity_reservation_display_name
// 		opt2 := _var.Compute_capacity_reservation_state
// 		_, err := oci.GetCoreComputeCapacityReservations(ctx, &GetCoreComputeCapacityReservationsArgs{
// 			CompartmentId:      _var.Compartment_id,
// 			AvailabilityDomain: &opt0,
// 			DisplayName:        &opt1,
// 			State:              &opt2,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetCoreComputeCapacityReservations(ctx *pulumi.Context, args *GetCoreComputeCapacityReservationsArgs, opts ...pulumi.InvokeOption) (*GetCoreComputeCapacityReservationsResult, error) {
	var rv GetCoreComputeCapacityReservationsResult
	err := ctx.Invoke("oci:index/getCoreComputeCapacityReservations:GetCoreComputeCapacityReservations", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetCoreComputeCapacityReservations.
type GetCoreComputeCapacityReservationsArgs struct {
	// The name of the availability domain.  Example: `Uocm:PHX-AD-1`
	AvailabilityDomain *string `pulumi:"availabilityDomain"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string `pulumi:"compartmentId"`
	// A filter to return only resources that match the given display name exactly.
	DisplayName *string                                    `pulumi:"displayName"`
	Filters     []GetCoreComputeCapacityReservationsFilter `pulumi:"filters"`
	// A filter to only return resources that match the given lifecycle state.
	State *string `pulumi:"state"`
}

// A collection of values returned by GetCoreComputeCapacityReservations.
type GetCoreComputeCapacityReservationsResult struct {
	// The availability domain of the compute capacity reservation.  Example: `Uocm:PHX-AD-1`
	AvailabilityDomain *string `pulumi:"availabilityDomain"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment containing the compute capacity reservation.
	CompartmentId string `pulumi:"compartmentId"`
	// The list of compute_capacity_reservations.
	ComputeCapacityReservations []GetCoreComputeCapacityReservationsComputeCapacityReservation `pulumi:"computeCapacityReservations"`
	// A user-friendly name for the capacity reservation. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: `My Reservation`
	DisplayName *string                                    `pulumi:"displayName"`
	Filters     []GetCoreComputeCapacityReservationsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The current state of the compute capacity reservation.
	State *string `pulumi:"state"`
}
