// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Functions in Oracle Cloud Infrastructure Functions service.
//
// Lists functions for an application.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := _var.Function_display_name
// 		opt1 := _var.Function_id
// 		opt2 := _var.Function_state
// 		_, err := oci.GetFunctionsFunctions(ctx, &GetFunctionsFunctionsArgs{
// 			ApplicationId: oci_functions_application.Test_application.Id,
// 			DisplayName:   &opt0,
// 			Id:            &opt1,
// 			State:         &opt2,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetFunctionsFunctions(ctx *pulumi.Context, args *GetFunctionsFunctionsArgs, opts ...pulumi.InvokeOption) (*GetFunctionsFunctionsResult, error) {
	var rv GetFunctionsFunctionsResult
	err := ctx.Invoke("oci:index/getFunctionsFunctions:GetFunctionsFunctions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetFunctionsFunctions.
type GetFunctionsFunctionsArgs struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the application to which this function belongs.
	ApplicationId string `pulumi:"applicationId"`
	// A filter to return only functions with display names that match the display name string. Matching is exact.
	DisplayName *string                       `pulumi:"displayName"`
	Filters     []GetFunctionsFunctionsFilter `pulumi:"filters"`
	// A filter to return only functions with the specified OCID.
	Id *string `pulumi:"id"`
	// A filter to return only functions that match the lifecycle state in this parameter. Example: `Creating`
	State *string `pulumi:"state"`
}

// A collection of values returned by GetFunctionsFunctions.
type GetFunctionsFunctionsResult struct {
	// The OCID of the application the function belongs to.
	ApplicationId string `pulumi:"applicationId"`
	// The display name of the function. The display name is unique within the application containing the function.
	DisplayName *string                       `pulumi:"displayName"`
	Filters     []GetFunctionsFunctionsFilter `pulumi:"filters"`
	// The list of functions.
	Functions []GetFunctionsFunctionsFunction `pulumi:"functions"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the function.
	Id *string `pulumi:"id"`
	// The current state of the function.
	State *string `pulumi:"state"`
}
