// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Api Keys in Oracle Cloud Infrastructure Identity service.
//
// Lists the API signing keys for the specified user. A user can have a maximum of three keys.
//
// Every user has permission to use this API call for *their own user ID*.  An administrator in your
// organization does not need to write a policy to give users this ability.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := oci.GetIdentityApiKeys(ctx, &GetIdentityApiKeysArgs{
// 			UserId: oci_identity_user.Test_user.Id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetIdentityApiKeys(ctx *pulumi.Context, args *GetIdentityApiKeysArgs, opts ...pulumi.InvokeOption) (*GetIdentityApiKeysResult, error) {
	var rv GetIdentityApiKeysResult
	err := ctx.Invoke("oci:index/getIdentityApiKeys:GetIdentityApiKeys", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetIdentityApiKeys.
type GetIdentityApiKeysArgs struct {
	Filters []GetIdentityApiKeysFilter `pulumi:"filters"`
	// The OCID of the user.
	UserId string `pulumi:"userId"`
}

// A collection of values returned by GetIdentityApiKeys.
type GetIdentityApiKeysResult struct {
	// The list of api_keys.
	ApiKeys []GetIdentityApiKeysApiKey `pulumi:"apiKeys"`
	Filters []GetIdentityApiKeysFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The OCID of the user the key belongs to.
	UserId string `pulumi:"userId"`
}
