// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides details about a specific Index resource in Oracle Cloud Infrastructure NoSQL Database service.
//
// Get information about a single index.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := oci.GetNosqlIndex(ctx, &GetNosqlIndexArgs{
// 			IndexName:     oci_nosql_index.Test_index.Name,
// 			TableNameOrId: oci_nosql_table_name_or.Test_table_name_or.Id,
// 			CompartmentId: _var.Compartment_id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupNosqlIndex(ctx *pulumi.Context, args *LookupNosqlIndexArgs, opts ...pulumi.InvokeOption) (*LookupNosqlIndexResult, error) {
	var rv LookupNosqlIndexResult
	err := ctx.Invoke("oci:index/getNosqlIndex:GetNosqlIndex", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetNosqlIndex.
type LookupNosqlIndexArgs struct {
	// The ID of a table's compartment. When a table is identified by name, the compartmentId is often needed to provide context for interpreting the name.
	CompartmentId string `pulumi:"compartmentId"`
	// The name of a table's index.
	IndexName string `pulumi:"indexName"`
	// A table name within the compartment, or a table OCID.
	TableNameOrId string `pulumi:"tableNameOrId"`
}

// A collection of values returned by GetNosqlIndex.
type LookupNosqlIndexResult struct {
	// Compartment Identifier.
	CompartmentId string `pulumi:"compartmentId"`
	Id            string `pulumi:"id"`
	IndexName     string `pulumi:"indexName"`
	IsIfNotExists bool   `pulumi:"isIfNotExists"`
	// A set of keys for a secondary index.
	Keys []GetNosqlIndexKey `pulumi:"keys"`
	// A message describing the current state in more detail.
	LifecycleDetails string `pulumi:"lifecycleDetails"`
	// Index name.
	Name string `pulumi:"name"`
	// The state of an index.
	State string `pulumi:"state"`
	// the OCID of the table to which this index belongs.
	TableId string `pulumi:"tableId"`
	// The name of the table to which this index belongs.
	TableName     string `pulumi:"tableName"`
	TableNameOrId string `pulumi:"tableNameOrId"`
}
