// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Notification Topics in Oracle Cloud Infrastructure Notifications service.
//
// Lists topics in the specified compartment.
//
// Transactions Per Minute (TPM) per-tenancy limit for this operation: 120.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := _var.Notification_topic_id
// 		opt1 := _var.Notification_topic_name
// 		opt2 := _var.Notification_topic_state
// 		_, err := oci.GetOnsNotificationTopics(ctx, &GetOnsNotificationTopicsArgs{
// 			CompartmentId: _var.Compartment_id,
// 			Id:            &opt0,
// 			Name:          &opt1,
// 			State:         &opt2,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetOnsNotificationTopics(ctx *pulumi.Context, args *GetOnsNotificationTopicsArgs, opts ...pulumi.InvokeOption) (*GetOnsNotificationTopicsResult, error) {
	var rv GetOnsNotificationTopicsResult
	err := ctx.Invoke("oci:index/getOnsNotificationTopics:GetOnsNotificationTopics", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetOnsNotificationTopics.
type GetOnsNotificationTopicsArgs struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string                           `pulumi:"compartmentId"`
	Filters       []GetOnsNotificationTopicsFilter `pulumi:"filters"`
	// A filter to only return resources that match the given id exactly.
	Id *string `pulumi:"id"`
	// A filter to only return resources that match the given name exactly.
	Name *string `pulumi:"name"`
	// Filter returned list by specified lifecycle state. This parameter is case-insensitive.
	State *string `pulumi:"state"`
}

// A collection of values returned by GetOnsNotificationTopics.
type GetOnsNotificationTopicsResult struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment for the topic.
	CompartmentId string                           `pulumi:"compartmentId"`
	Filters       []GetOnsNotificationTopicsFilter `pulumi:"filters"`
	Id            *string                          `pulumi:"id"`
	// The name of the topic.
	Name *string `pulumi:"name"`
	// The list of notification_topics.
	NotificationTopics []GetOnsNotificationTopicsNotificationTopic `pulumi:"notificationTopics"`
	// The lifecycle state of the topic.
	State *string `pulumi:"state"`
}
