// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package oci

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Subscriptions in Oracle Cloud Infrastructure Notifications service.
//
// Lists the subscriptions in the specified compartment or topic.
//
// Transactions Per Minute (TPM) per-tenancy limit for this operation: 60.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := oci_ons_notification_topic.Test_notification_topic.Id
// 		_, err := oci.GetOnsSubscriptions(ctx, &GetOnsSubscriptionsArgs{
// 			CompartmentId: _var.Compartment_id,
// 			TopicId:       &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetOnsSubscriptions(ctx *pulumi.Context, args *GetOnsSubscriptionsArgs, opts ...pulumi.InvokeOption) (*GetOnsSubscriptionsResult, error) {
	var rv GetOnsSubscriptionsResult
	err := ctx.Invoke("oci:index/getOnsSubscriptions:GetOnsSubscriptions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetOnsSubscriptions.
type GetOnsSubscriptionsArgs struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string                      `pulumi:"compartmentId"`
	Filters       []GetOnsSubscriptionsFilter `pulumi:"filters"`
	// Return all subscriptions that are subscribed to the given topic OCID. Either this query parameter or the compartmentId query parameter must be set.
	TopicId *string `pulumi:"topicId"`
}

// A collection of values returned by GetOnsSubscriptions.
type GetOnsSubscriptionsResult struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment for the subscription.
	CompartmentId string                      `pulumi:"compartmentId"`
	Filters       []GetOnsSubscriptionsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The list of subscriptions.
	Subscriptions []GetOnsSubscriptionsSubscription `pulumi:"subscriptions"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the associated topic.
	TopicId *string `pulumi:"topicId"`
}
