// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databasemigration

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Connections in Oracle Cloud Infrastructure Database Migration service.
//
// List all Database Connections.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci/databasemigration"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := _var.Connection_display_name
// 		opt1 := _var.Connection_state
// 		_, err := databasemigration.GetConnections(ctx, &databasemigration.GetConnectionsArgs{
// 			CompartmentId: _var.Compartment_id,
// 			DisplayName:   &opt0,
// 			State:         &opt1,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetConnections(ctx *pulumi.Context, args *GetConnectionsArgs, opts ...pulumi.InvokeOption) (*GetConnectionsResult, error) {
	var rv GetConnectionsResult
	err := ctx.Invoke("oci:databasemigration/getConnections:getConnections", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getConnections.
type GetConnectionsArgs struct {
	// The ID of the compartment in which to list resources.
	CompartmentId string `pulumi:"compartmentId"`
	// A filter to return only resources that match the entire display name given.
	DisplayName *string                `pulumi:"displayName"`
	Filters     []GetConnectionsFilter `pulumi:"filters"`
	// The current state of the Database Migration Deployment.
	State *string `pulumi:"state"`
}

// A collection of values returned by getConnections.
type GetConnectionsResult struct {
	// OCID of the compartment where the secret containing the credentials will be created.
	CompartmentId string `pulumi:"compartmentId"`
	// The list of connection_collection.
	ConnectionCollections []GetConnectionsConnectionCollection `pulumi:"connectionCollections"`
	// Database Connection display name identifier.
	DisplayName *string                `pulumi:"displayName"`
	Filters     []GetConnectionsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The current state of the Connection resource.
	State *string `pulumi:"state"`
}
