// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package loganalytics

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides details about a specific Log Analytics Log Group resource in Oracle Cloud Infrastructure Log Analytics service.
//
// Gets detailed information about the specified log group such as display name, description, defined tags, and free-form tags.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci/loganalytics"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := loganalytics.LookupLogAnalyticsLogGroup(ctx, &loganalytics.LookupLogAnalyticsLogGroupArgs{
// 			LogAnalyticsLogGroupId: oci_log_analytics_log_analytics_log_group.Test_log_analytics_log_group.Id,
// 			Namespace:              _var.Log_analytics_log_group_namespace,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupLogAnalyticsLogGroup(ctx *pulumi.Context, args *LookupLogAnalyticsLogGroupArgs, opts ...pulumi.InvokeOption) (*LookupLogAnalyticsLogGroupResult, error) {
	var rv LookupLogAnalyticsLogGroupResult
	err := ctx.Invoke("oci:loganalytics/getLogAnalyticsLogGroup:getLogAnalyticsLogGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLogAnalyticsLogGroup.
type LookupLogAnalyticsLogGroupArgs struct {
	// unique logAnalytics log group identifier
	LogAnalyticsLogGroupId string `pulumi:"logAnalyticsLogGroupId"`
	// The Logging Analytics namespace used for the request.
	Namespace string `pulumi:"namespace"`
}

// A collection of values returned by getLogAnalyticsLogGroup.
type LookupLogAnalyticsLogGroupResult struct {
	// Compartment Identifier [OCID] (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	CompartmentId string `pulumi:"compartmentId"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: `{"foo-namespace.bar-key": "value"}`
	DefinedTags map[string]interface{} `pulumi:"definedTags"`
	// Description for this resource.
	Description string `pulumi:"description"`
	// A user-friendly name that is changeable and that does not have to be unique. Format: a leading alphanumeric, followed by zero or more alphanumerics, underscores, spaces, backslashes, or hyphens in any order). No trailing spaces allowed.
	DisplayName string `pulumi:"displayName"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: `{"bar-key": "value"}`
	FreeformTags map[string]interface{} `pulumi:"freeformTags"`
	// The log analytics entity OCID. This ID is a reference used by log analytics features and it represents a resource that is provisioned and managed by the customer on their premises or on the cloud.
	Id                     string `pulumi:"id"`
	LogAnalyticsLogGroupId string `pulumi:"logAnalyticsLogGroupId"`
	Namespace              string `pulumi:"namespace"`
	// The date and time the resource was created, in the format defined by RFC3339.
	TimeCreated string `pulumi:"timeCreated"`
	// The date and time the resource was last updated, in the format defined by RFC3339.
	TimeUpdated string `pulumi:"timeUpdated"`
}
