// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class CoreVolumeGroupSourceDetails
    {
        /// <summary>
        /// The type can be one of these values: `volumeGroupBackupId`, `volumeGroupId`, `volumeIds`
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The OCID of the volume group backup to restore from.
        /// </summary>
        public readonly string? VolumeGroupBackupId;
        /// <summary>
        /// The OCID of the volume group to clone from.
        /// </summary>
        public readonly string? VolumeGroupId;
        /// <summary>
        /// OCIDs for the volumes in this volume group.
        /// </summary>
        public readonly ImmutableArray<string> VolumeIds;

        [OutputConstructor]
        private CoreVolumeGroupSourceDetails(
            string type,

            string? volumeGroupBackupId,

            string? volumeGroupId,

            ImmutableArray<string> volumeIds)
        {
            Type = type;
            VolumeGroupBackupId = volumeGroupBackupId;
            VolumeGroupId = volumeGroupId;
            VolumeIds = volumeIds;
        }
    }
}
