// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class CoreInstanceConfigurationInstanceDetailsBlockVolumeCreateDetailsSourceDetails
    {
        /// <summary>
        /// The OCID of the volume backup.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The type of action to run when the instance is interrupted for eviction.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private CoreInstanceConfigurationInstanceDetailsBlockVolumeCreateDetailsSourceDetails(
            string? id,

            string type)
        {
            Id = id;
            Type = type;
        }
    }
}
