// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetBdsAutoScalingConfigurationsAutoScalingConfigurationPolicyResult
    {
        public readonly string PolicyType;
        public readonly ImmutableArray<Outputs.GetBdsAutoScalingConfigurationsAutoScalingConfigurationPolicyRuleResult> Rules;

        [OutputConstructor]
        private GetBdsAutoScalingConfigurationsAutoScalingConfigurationPolicyResult(
            string policyType,

            ImmutableArray<Outputs.GetBdsAutoScalingConfigurationsAutoScalingConfigurationPolicyRuleResult> rules)
        {
            PolicyType = policyType;
            Rules = rules;
        }
    }
}
