// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetDatabaseAutonomousDatabaseCustomerContactResult
    {
        /// <summary>
        /// The email address used by Oracle to send notifications regarding databases and infrastructure.
        /// </summary>
        public readonly string Email;

        [OutputConstructor]
        private GetDatabaseAutonomousDatabaseCustomerContactResult(string email)
        {
            Email = email;
        }
    }
}
