// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetDevopsDeployStagesDeployStageCollectionItemDeployStagePredecessorCollectionResult
    {
        /// <summary>
        /// The IP address of the backend server. A server could be a compute instance or a load balancer.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDevopsDeployStagesDeployStageCollectionItemDeployStagePredecessorCollectionItemResult> Items;

        [OutputConstructor]
        private GetDevopsDeployStagesDeployStageCollectionItemDeployStagePredecessorCollectionResult(ImmutableArray<Outputs.GetDevopsDeployStagesDeployStageCollectionItemDeployStagePredecessorCollectionItemResult> items)
        {
            Items = items;
        }
    }
}
