// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetDatabaseDbSystemsDbSystemDbHomeDatabaseResult
    {
        public readonly string AdminPassword;
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the backup. Specify a backupId to list only the DB systems or DB homes that support creating a database using this backup in this compartment.
        /// </summary>
        public readonly string BackupId;
        public readonly string BackupTdePassword;
        public readonly string CharacterSet;
        public readonly ImmutableArray<Outputs.GetDatabaseDbSystemsDbSystemDbHomeDatabaseConnectionStringResult> ConnectionStrings;
        public readonly string DatabaseId;
        public readonly string DatabaseSoftwareImageId;
        public readonly Outputs.GetDatabaseDbSystemsDbSystemDbHomeDatabaseDbBackupConfigResult DbBackupConfig;
        public readonly string DbDomain;
        public readonly string DbName;
        public readonly string DbUniqueName;
        public readonly string DbWorkload;
        /// <summary>
        /// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
        /// </summary>
        public readonly ImmutableDictionary<string, object> DefinedTags;
        /// <summary>
        /// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).  Example: `{"Department": "Finance"}`
        /// </summary>
        public readonly ImmutableDictionary<string, object> FreeformTags;
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Additional information about the current lifecycle state.
        /// </summary>
        public readonly string LifecycleDetails;
        public readonly string NcharacterSet;
        public readonly string PdbName;
        /// <summary>
        /// A filter to return only resources that match the given lifecycle state exactly.
        /// </summary>
        public readonly string State;
        public readonly string TdeWalletPassword;
        /// <summary>
        /// The date and time the DB system was created.
        /// </summary>
        public readonly string TimeCreated;
        public readonly string TimeStampForPointInTimeRecovery;

        [OutputConstructor]
        private GetDatabaseDbSystemsDbSystemDbHomeDatabaseResult(
            string adminPassword,

            string backupId,

            string backupTdePassword,

            string characterSet,

            ImmutableArray<Outputs.GetDatabaseDbSystemsDbSystemDbHomeDatabaseConnectionStringResult> connectionStrings,

            string databaseId,

            string databaseSoftwareImageId,

            Outputs.GetDatabaseDbSystemsDbSystemDbHomeDatabaseDbBackupConfigResult dbBackupConfig,

            string dbDomain,

            string dbName,

            string dbUniqueName,

            string dbWorkload,

            ImmutableDictionary<string, object> definedTags,

            ImmutableDictionary<string, object> freeformTags,

            string id,

            string lifecycleDetails,

            string ncharacterSet,

            string pdbName,

            string state,

            string tdeWalletPassword,

            string timeCreated,

            string timeStampForPointInTimeRecovery)
        {
            AdminPassword = adminPassword;
            BackupId = backupId;
            BackupTdePassword = backupTdePassword;
            CharacterSet = characterSet;
            ConnectionStrings = connectionStrings;
            DatabaseId = databaseId;
            DatabaseSoftwareImageId = databaseSoftwareImageId;
            DbBackupConfig = dbBackupConfig;
            DbDomain = dbDomain;
            DbName = dbName;
            DbUniqueName = dbUniqueName;
            DbWorkload = dbWorkload;
            DefinedTags = definedTags;
            FreeformTags = freeformTags;
            Id = id;
            LifecycleDetails = lifecycleDetails;
            NcharacterSet = ncharacterSet;
            PdbName = pdbName;
            State = state;
            TdeWalletPassword = tdeWalletPassword;
            TimeCreated = timeCreated;
            TimeStampForPointInTimeRecovery = timeStampForPointInTimeRecovery;
        }
    }
}
