// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetDatabaseMigrationMigrationsMigrationCollectionItemDatapumpSettingsMetadataRemapResult
    {
        /// <summary>
        /// Specifies the new value that oldValue should be translated into.
        /// </summary>
        public readonly string NewValue;
        /// <summary>
        /// Specifies the value which needs to be reset.
        /// </summary>
        public readonly string OldValue;
        /// <summary>
        /// Migration type.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetDatabaseMigrationMigrationsMigrationCollectionItemDatapumpSettingsMetadataRemapResult(
            string newValue,

            string oldValue,

            string type)
        {
            NewValue = newValue;
            OldValue = oldValue;
            Type = type;
        }
    }
}
