// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetDatabaseDbSystemsDbSystemDbHomeDatabaseDbBackupConfigBackupDestinationDetailResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system.
        /// </summary>
        public readonly string Id;
        public readonly string Type;

        [OutputConstructor]
        private GetDatabaseDbSystemsDbSystemDbHomeDatabaseDbBackupConfigBackupDestinationDetailResult(
            string id,

            string type)
        {
            Id = id;
            Type = type;
        }
    }
}
