// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetLoadBalancerLoadBalancerRoutingPoliciesRoutingPolicyResult
    {
        /// <summary>
        /// The version of the language in which `condition` of `rules` are composed.
        /// </summary>
        public readonly string ConditionLanguageVersion;
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the load balancer associated with the routing policies.
        /// </summary>
        public readonly string LoadBalancerId;
        /// <summary>
        /// A unique name for the routing policy rule. Avoid entering confidential information.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ordered list of routing rules.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetLoadBalancerLoadBalancerRoutingPoliciesRoutingPolicyRuleResult> Rules;
        public readonly string State;

        [OutputConstructor]
        private GetLoadBalancerLoadBalancerRoutingPoliciesRoutingPolicyResult(
            string conditionLanguageVersion,

            string loadBalancerId,

            string name,

            ImmutableArray<Outputs.GetLoadBalancerLoadBalancerRoutingPoliciesRoutingPolicyRuleResult> rules,

            string state)
        {
            ConditionLanguageVersion = conditionLanguageVersion;
            LoadBalancerId = loadBalancerId;
            Name = name;
            Rules = rules;
            State = state;
        }
    }
}
