// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Outputs
{

    [OutputType]
    public sealed class GetOptimizerProfileTargetTagsResult
    {
        /// <summary>
        /// The list of target tags attached to the current profile override.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetOptimizerProfileTargetTagsItemResult> Items;

        [OutputConstructor]
        private GetOptimizerProfileTargetTagsResult(ImmutableArray<Outputs.GetOptimizerProfileTargetTagsItemResult> items)
        {
            Items = items;
        }
    }
}
