// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source provides the list of Managed Databases in Oracle Cloud Infrastructure Database Management service.
 *
 * Gets the Managed Database for a specific ID or the list of Managed Databases in a specific compartment.
 * Managed Databases can also be filtered based on the name parameter. Only one of the parameters, ID or name
 * should be provided. If none of these parameters is provided, all the Managed Databases in the compartment are listed.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testManagedDatabases = oci.databasemanagement.getManagedDatabases({
 *     compartmentId: _var.compartment_id,
 *     id: _var.managed_database_id,
 *     name: _var.managed_database_name,
 * });
 * ```
 */
export function getManagedDatabases(args: GetManagedDatabasesArgs, opts?: pulumi.InvokeOptions): Promise<GetManagedDatabasesResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("oci:databasemanagement/getManagedDatabases:getManagedDatabases", {
        "compartmentId": args.compartmentId,
        "filters": args.filters,
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getManagedDatabases.
 */
export interface GetManagedDatabasesArgs {
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
     */
    compartmentId: string;
    filters?: inputs.databasemanagement.GetManagedDatabasesFilter[];
    /**
     * The identifier of the resource.
     */
    id?: string;
    /**
     * A filter to return only resources that match the entire name.
     */
    name?: string;
}

/**
 * A collection of values returned by getManagedDatabases.
 */
export interface GetManagedDatabasesResult {
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the Managed Database Group resides.
     */
    readonly compartmentId: string;
    readonly filters?: outputs.databasemanagement.GetManagedDatabasesFilter[];
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database Group.
     */
    readonly id?: string;
    /**
     * The list of managed_database_collection.
     */
    readonly managedDatabaseCollections: outputs.databasemanagement.GetManagedDatabasesManagedDatabaseCollection[];
    /**
     * The name of the Managed Database.
     */
    readonly name?: string;
}
