// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./getManagedDatabase";
export * from "./getManagedDatabaseGroup";
export * from "./getManagedDatabaseGroups";
export * from "./getManagedDatabases";
export * from "./getManagedDatabasesDatabaseParameter";
export * from "./getManagedDatabasesDatabaseParameters";
export * from "./managedDatabaseGroup";
export * from "./managedDatabasesChangeDatabaseParameter";
export * from "./managedDatabasesResetDatabaseParameter";

// Import resources to register:
import { ManagedDatabaseGroup } from "./managedDatabaseGroup";
import { ManagedDatabasesChangeDatabaseParameter } from "./managedDatabasesChangeDatabaseParameter";
import { ManagedDatabasesResetDatabaseParameter } from "./managedDatabasesResetDatabaseParameter";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "oci:databasemanagement/managedDatabaseGroup:ManagedDatabaseGroup":
                return new ManagedDatabaseGroup(name, <any>undefined, { urn })
            case "oci:databasemanagement/managedDatabasesChangeDatabaseParameter:ManagedDatabasesChangeDatabaseParameter":
                return new ManagedDatabasesChangeDatabaseParameter(name, <any>undefined, { urn })
            case "oci:databasemanagement/managedDatabasesResetDatabaseParameter:ManagedDatabasesResetDatabaseParameter":
                return new ManagedDatabasesResetDatabaseParameter(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("oci", "databasemanagement/managedDatabaseGroup", _module)
pulumi.runtime.registerResourceModule("oci", "databasemanagement/managedDatabasesChangeDatabaseParameter", _module)
pulumi.runtime.registerResourceModule("oci", "databasemanagement/managedDatabasesResetDatabaseParameter", _module)
