// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package dataflow

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Run Logs in Oracle Cloud Infrastructure Data Flow service.
//
// Retrieves summaries of the run's logs.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci/dataflow"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := dataflow.GetRunLogs(ctx, &dataflow.GetRunLogsArgs{
// 			RunId: oci_dataflow_run.Test_run.Id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetRunLogs(ctx *pulumi.Context, args *GetRunLogsArgs, opts ...pulumi.InvokeOption) (*GetRunLogsResult, error) {
	var rv GetRunLogsResult
	err := ctx.Invoke("oci:dataflow/getRunLogs:getRunLogs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRunLogs.
type GetRunLogsArgs struct {
	Filters []GetRunLogsFilter `pulumi:"filters"`
	// The unique ID for the run
	RunId string `pulumi:"runId"`
}

// A collection of values returned by getRunLogs.
type GetRunLogsResult struct {
	Filters []GetRunLogsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id    string `pulumi:"id"`
	RunId string `pulumi:"runId"`
	// The list of run_logs.
	RunLogs []GetRunLogsRunLog `pulumi:"runLogs"`
}
