// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.DataScience.Outputs
{

    [OutputType]
    public sealed class GetModelDeploymentsModelDeploymentModelDeploymentConfigurationDetailsResult
    {
        /// <summary>
        /// The type of the model deployment.
        /// </summary>
        public readonly string DeploymentType;
        /// <summary>
        /// The model configuration details.
        /// </summary>
        public readonly Outputs.GetModelDeploymentsModelDeploymentModelDeploymentConfigurationDetailsModelConfigurationDetailsResult ModelConfigurationDetails;

        [OutputConstructor]
        private GetModelDeploymentsModelDeploymentModelDeploymentConfigurationDetailsResult(
            string deploymentType,

            Outputs.GetModelDeploymentsModelDeploymentModelDeploymentConfigurationDetailsModelConfigurationDetailsResult modelConfigurationDetails)
        {
            DeploymentType = deploymentType;
            ModelConfigurationDetails = modelConfigurationDetails;
        }
    }
}
