// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source provides the list of Backups in Oracle Cloud Infrastructure Database service.
 *
 * Gets a list of backups based on the `databaseId` or `compartmentId` specified. Either one of these query parameters must be provided.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testBackups = oci.database.getBackups({
 *     compartmentId: _var.compartment_id,
 *     databaseId: oci_database_database.test_database.id,
 * });
 * ```
 */
export function getBackups(args?: GetBackupsArgs, opts?: pulumi.InvokeOptions): Promise<GetBackupsResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("oci:database/getBackups:getBackups", {
        "compartmentId": args.compartmentId,
        "databaseId": args.databaseId,
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsArgs {
    /**
     * The compartment [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
     */
    compartmentId?: string;
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the database.
     */
    databaseId?: string;
    filters?: inputs.database.GetBackupsFilter[];
}

/**
 * A collection of values returned by getBackups.
 */
export interface GetBackupsResult {
    /**
     * The list of backups.
     */
    readonly backups: outputs.database.GetBackupsBackup[];
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
     */
    readonly compartmentId?: string;
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the database.
     */
    readonly databaseId?: string;
    readonly filters?: outputs.database.GetBackupsFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
