// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./autonomousContainerDatabase";
export * from "./autonomousContainerDatabaseDataguardAssociationOperation";
export * from "./autonomousDatabase";
export * from "./autonomousDatabaseBackup";
export * from "./autonomousDatabaseInstanceWalletManagement";
export * from "./autonomousDatabaseRegionalWalletManagement";
export * from "./autonomousDatabaseWallet";
export * from "./autonomousExadataInfrastructure";
export * from "./autonomousVmCluster";
export * from "./backup";
export * from "./backupDestination";
export * from "./cloudExadataInfrastructure";
export * from "./cloudVmCluster";
export * from "./dataGuardAssociation";
export * from "./database";
export * from "./databaseSoftwareImage";
export * from "./databaseUpgrade";
export * from "./dbHome";
export * from "./dbNodeConsoleConnection";
export * from "./dbSystem";
export * from "./exadataInfrastructure";
export * from "./exadataIormConfig";
export * from "./externalContainerDatabase";
export * from "./externalContainerDatabaseManagement";
export * from "./externalDatabaseConnector";
export * from "./externalNonContainerDatabase";
export * from "./externalNonContainerDatabaseManagement";
export * from "./externalNonContainerDatabaseOperationsInsightsManagement";
export * from "./externalPluggableDatabase";
export * from "./externalPluggableDatabaseManagement";
export * from "./externalPluggableDatabaseOperationsInsightsManagement";
export * from "./getAutonomousContainerDatabase";
export * from "./getAutonomousContainerDatabaseDataguardAssociation";
export * from "./getAutonomousContainerDatabaseDataguardAssociations";
export * from "./getAutonomousContainerDatabases";
export * from "./getAutonomousContainerPatches";
export * from "./getAutonomousDatabase";
export * from "./getAutonomousDatabaseBackup";
export * from "./getAutonomousDatabaseBackups";
export * from "./getAutonomousDatabaseDataguardAssociation";
export * from "./getAutonomousDatabaseDataguardAssociations";
export * from "./getAutonomousDatabaseInstanceWalletManagement";
export * from "./getAutonomousDatabaseRegionalWalletManagement";
export * from "./getAutonomousDatabaseWallet";
export * from "./getAutonomousDatabases";
export * from "./getAutonomousDatabasesClones";
export * from "./getAutonomousDbPreviewVersions";
export * from "./getAutonomousDbVersions";
export * from "./getAutonomousExadataInfrastructure";
export * from "./getAutonomousExadataInfrastructureOcpu";
export * from "./getAutonomousExadataInfrastructureShapes";
export * from "./getAutonomousExadataInfrastructures";
export * from "./getAutonomousPatch";
export * from "./getAutonomousVmCluster";
export * from "./getAutonomousVmClusters";
export * from "./getBackupDestination";
export * from "./getBackupDestinations";
export * from "./getBackups";
export * from "./getCloudExadataInfrastructure";
export * from "./getCloudExadataInfrastructures";
export * from "./getCloudVmCluster";
export * from "./getCloudVmClusters";
export * from "./getDataGuardAssociation";
export * from "./getDataGuardAssociations";
export * from "./getDatabase";
export * from "./getDatabaseSoftwareImage";
export * from "./getDatabaseSoftwareImages";
export * from "./getDatabaseUpgradeHistoryEntries";
export * from "./getDatabaseUpgradeHistoryEntry";
export * from "./getDatabases";
export * from "./getDbHome";
export * from "./getDbHomePatchHistoryEntries";
export * from "./getDbHomePatches";
export * from "./getDbHomes";
export * from "./getDbNode";
export * from "./getDbNodeConsoleConnection";
export * from "./getDbNodeConsoleConnections";
export * from "./getDbNodes";
export * from "./getDbSystemPatchHistoryEntries";
export * from "./getDbSystemPatches";
export * from "./getDbSystemShapes";
export * from "./getDbSystems";
export * from "./getDbVersions";
export * from "./getExadataInfrastructure";
export * from "./getExadataInfrastructureDownloadConfigFile";
export * from "./getExadataInfrastructures";
export * from "./getExadataIormConfig";
export * from "./getExternalContainerDatabase";
export * from "./getExternalContainerDatabases";
export * from "./getExternalDatabaseConnector";
export * from "./getExternalDatabaseConnectors";
export * from "./getExternalNonContainerDatabase";
export * from "./getExternalNonContainerDatabases";
export * from "./getExternalPluggableDatabase";
export * from "./getExternalPluggableDatabases";
export * from "./getFlexComponents";
export * from "./getGiVersions";
export * from "./getKeyStore";
export * from "./getKeyStores";
export * from "./getMaintenanceRun";
export * from "./getMaintenanceRuns";
export * from "./getPluggableDatabase";
export * from "./getPluggableDatabases";
export * from "./getVmCluster";
export * from "./getVmClusterNetwork";
export * from "./getVmClusterNetworkDownloadConfigFile";
export * from "./getVmClusterNetworks";
export * from "./getVmClusterPatch";
export * from "./getVmClusterPatchHistoryEntries";
export * from "./getVmClusterPatchHistoryEntry";
export * from "./getVmClusterPatches";
export * from "./getVmClusterRecommendedNetwork";
export * from "./getVmClusterUpdate";
export * from "./getVmClusterUpdateHistoryEntries";
export * from "./getVmClusterUpdateHistoryEntry";
export * from "./getVmClusterUpdates";
export * from "./getVmClusters";
export * from "./keyStore";
export * from "./maintenanceRun";
export * from "./migration";
export * from "./pluggableDatabase";
export * from "./pluggableDatabasesLocalClone";
export * from "./pluggableDatabasesRemoteClone";
export * from "./vmCluster";
export * from "./vmClusterNetwork";

// Import resources to register:
import { AutonomousContainerDatabase } from "./autonomousContainerDatabase";
import { AutonomousContainerDatabaseDataguardAssociationOperation } from "./autonomousContainerDatabaseDataguardAssociationOperation";
import { AutonomousDatabase } from "./autonomousDatabase";
import { AutonomousDatabaseBackup } from "./autonomousDatabaseBackup";
import { AutonomousDatabaseInstanceWalletManagement } from "./autonomousDatabaseInstanceWalletManagement";
import { AutonomousDatabaseRegionalWalletManagement } from "./autonomousDatabaseRegionalWalletManagement";
import { AutonomousDatabaseWallet } from "./autonomousDatabaseWallet";
import { AutonomousExadataInfrastructure } from "./autonomousExadataInfrastructure";
import { AutonomousVmCluster } from "./autonomousVmCluster";
import { Backup } from "./backup";
import { BackupDestination } from "./backupDestination";
import { CloudExadataInfrastructure } from "./cloudExadataInfrastructure";
import { CloudVmCluster } from "./cloudVmCluster";
import { DataGuardAssociation } from "./dataGuardAssociation";
import { Database } from "./database";
import { DatabaseSoftwareImage } from "./databaseSoftwareImage";
import { DatabaseUpgrade } from "./databaseUpgrade";
import { DbHome } from "./dbHome";
import { DbNodeConsoleConnection } from "./dbNodeConsoleConnection";
import { DbSystem } from "./dbSystem";
import { ExadataInfrastructure } from "./exadataInfrastructure";
import { ExadataIormConfig } from "./exadataIormConfig";
import { ExternalContainerDatabase } from "./externalContainerDatabase";
import { ExternalContainerDatabaseManagement } from "./externalContainerDatabaseManagement";
import { ExternalDatabaseConnector } from "./externalDatabaseConnector";
import { ExternalNonContainerDatabase } from "./externalNonContainerDatabase";
import { ExternalNonContainerDatabaseManagement } from "./externalNonContainerDatabaseManagement";
import { ExternalNonContainerDatabaseOperationsInsightsManagement } from "./externalNonContainerDatabaseOperationsInsightsManagement";
import { ExternalPluggableDatabase } from "./externalPluggableDatabase";
import { ExternalPluggableDatabaseManagement } from "./externalPluggableDatabaseManagement";
import { ExternalPluggableDatabaseOperationsInsightsManagement } from "./externalPluggableDatabaseOperationsInsightsManagement";
import { KeyStore } from "./keyStore";
import { MaintenanceRun } from "./maintenanceRun";
import { Migration } from "./migration";
import { PluggableDatabase } from "./pluggableDatabase";
import { PluggableDatabasesLocalClone } from "./pluggableDatabasesLocalClone";
import { PluggableDatabasesRemoteClone } from "./pluggableDatabasesRemoteClone";
import { VmCluster } from "./vmCluster";
import { VmClusterNetwork } from "./vmClusterNetwork";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "oci:database/autonomousContainerDatabase:AutonomousContainerDatabase":
                return new AutonomousContainerDatabase(name, <any>undefined, { urn })
            case "oci:database/autonomousContainerDatabaseDataguardAssociationOperation:AutonomousContainerDatabaseDataguardAssociationOperation":
                return new AutonomousContainerDatabaseDataguardAssociationOperation(name, <any>undefined, { urn })
            case "oci:database/autonomousDatabase:AutonomousDatabase":
                return new AutonomousDatabase(name, <any>undefined, { urn })
            case "oci:database/autonomousDatabaseBackup:AutonomousDatabaseBackup":
                return new AutonomousDatabaseBackup(name, <any>undefined, { urn })
            case "oci:database/autonomousDatabaseInstanceWalletManagement:AutonomousDatabaseInstanceWalletManagement":
                return new AutonomousDatabaseInstanceWalletManagement(name, <any>undefined, { urn })
            case "oci:database/autonomousDatabaseRegionalWalletManagement:AutonomousDatabaseRegionalWalletManagement":
                return new AutonomousDatabaseRegionalWalletManagement(name, <any>undefined, { urn })
            case "oci:database/autonomousDatabaseWallet:AutonomousDatabaseWallet":
                return new AutonomousDatabaseWallet(name, <any>undefined, { urn })
            case "oci:database/autonomousExadataInfrastructure:AutonomousExadataInfrastructure":
                return new AutonomousExadataInfrastructure(name, <any>undefined, { urn })
            case "oci:database/autonomousVmCluster:AutonomousVmCluster":
                return new AutonomousVmCluster(name, <any>undefined, { urn })
            case "oci:database/backup:Backup":
                return new Backup(name, <any>undefined, { urn })
            case "oci:database/backupDestination:BackupDestination":
                return new BackupDestination(name, <any>undefined, { urn })
            case "oci:database/cloudExadataInfrastructure:CloudExadataInfrastructure":
                return new CloudExadataInfrastructure(name, <any>undefined, { urn })
            case "oci:database/cloudVmCluster:CloudVmCluster":
                return new CloudVmCluster(name, <any>undefined, { urn })
            case "oci:database/dataGuardAssociation:DataGuardAssociation":
                return new DataGuardAssociation(name, <any>undefined, { urn })
            case "oci:database/database:Database":
                return new Database(name, <any>undefined, { urn })
            case "oci:database/databaseSoftwareImage:DatabaseSoftwareImage":
                return new DatabaseSoftwareImage(name, <any>undefined, { urn })
            case "oci:database/databaseUpgrade:DatabaseUpgrade":
                return new DatabaseUpgrade(name, <any>undefined, { urn })
            case "oci:database/dbHome:DbHome":
                return new DbHome(name, <any>undefined, { urn })
            case "oci:database/dbNodeConsoleConnection:DbNodeConsoleConnection":
                return new DbNodeConsoleConnection(name, <any>undefined, { urn })
            case "oci:database/dbSystem:DbSystem":
                return new DbSystem(name, <any>undefined, { urn })
            case "oci:database/exadataInfrastructure:ExadataInfrastructure":
                return new ExadataInfrastructure(name, <any>undefined, { urn })
            case "oci:database/exadataIormConfig:ExadataIormConfig":
                return new ExadataIormConfig(name, <any>undefined, { urn })
            case "oci:database/externalContainerDatabase:ExternalContainerDatabase":
                return new ExternalContainerDatabase(name, <any>undefined, { urn })
            case "oci:database/externalContainerDatabaseManagement:ExternalContainerDatabaseManagement":
                return new ExternalContainerDatabaseManagement(name, <any>undefined, { urn })
            case "oci:database/externalDatabaseConnector:ExternalDatabaseConnector":
                return new ExternalDatabaseConnector(name, <any>undefined, { urn })
            case "oci:database/externalNonContainerDatabase:ExternalNonContainerDatabase":
                return new ExternalNonContainerDatabase(name, <any>undefined, { urn })
            case "oci:database/externalNonContainerDatabaseManagement:ExternalNonContainerDatabaseManagement":
                return new ExternalNonContainerDatabaseManagement(name, <any>undefined, { urn })
            case "oci:database/externalNonContainerDatabaseOperationsInsightsManagement:ExternalNonContainerDatabaseOperationsInsightsManagement":
                return new ExternalNonContainerDatabaseOperationsInsightsManagement(name, <any>undefined, { urn })
            case "oci:database/externalPluggableDatabase:ExternalPluggableDatabase":
                return new ExternalPluggableDatabase(name, <any>undefined, { urn })
            case "oci:database/externalPluggableDatabaseManagement:ExternalPluggableDatabaseManagement":
                return new ExternalPluggableDatabaseManagement(name, <any>undefined, { urn })
            case "oci:database/externalPluggableDatabaseOperationsInsightsManagement:ExternalPluggableDatabaseOperationsInsightsManagement":
                return new ExternalPluggableDatabaseOperationsInsightsManagement(name, <any>undefined, { urn })
            case "oci:database/keyStore:KeyStore":
                return new KeyStore(name, <any>undefined, { urn })
            case "oci:database/maintenanceRun:MaintenanceRun":
                return new MaintenanceRun(name, <any>undefined, { urn })
            case "oci:database/migration:Migration":
                return new Migration(name, <any>undefined, { urn })
            case "oci:database/pluggableDatabase:PluggableDatabase":
                return new PluggableDatabase(name, <any>undefined, { urn })
            case "oci:database/pluggableDatabasesLocalClone:PluggableDatabasesLocalClone":
                return new PluggableDatabasesLocalClone(name, <any>undefined, { urn })
            case "oci:database/pluggableDatabasesRemoteClone:PluggableDatabasesRemoteClone":
                return new PluggableDatabasesRemoteClone(name, <any>undefined, { urn })
            case "oci:database/vmCluster:VmCluster":
                return new VmCluster(name, <any>undefined, { urn })
            case "oci:database/vmClusterNetwork:VmClusterNetwork":
                return new VmClusterNetwork(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("oci", "database/autonomousContainerDatabase", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousContainerDatabaseDataguardAssociationOperation", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousDatabase", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousDatabaseBackup", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousDatabaseInstanceWalletManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousDatabaseRegionalWalletManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousDatabaseWallet", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousExadataInfrastructure", _module)
pulumi.runtime.registerResourceModule("oci", "database/autonomousVmCluster", _module)
pulumi.runtime.registerResourceModule("oci", "database/backup", _module)
pulumi.runtime.registerResourceModule("oci", "database/backupDestination", _module)
pulumi.runtime.registerResourceModule("oci", "database/cloudExadataInfrastructure", _module)
pulumi.runtime.registerResourceModule("oci", "database/cloudVmCluster", _module)
pulumi.runtime.registerResourceModule("oci", "database/dataGuardAssociation", _module)
pulumi.runtime.registerResourceModule("oci", "database/database", _module)
pulumi.runtime.registerResourceModule("oci", "database/databaseSoftwareImage", _module)
pulumi.runtime.registerResourceModule("oci", "database/databaseUpgrade", _module)
pulumi.runtime.registerResourceModule("oci", "database/dbHome", _module)
pulumi.runtime.registerResourceModule("oci", "database/dbNodeConsoleConnection", _module)
pulumi.runtime.registerResourceModule("oci", "database/dbSystem", _module)
pulumi.runtime.registerResourceModule("oci", "database/exadataInfrastructure", _module)
pulumi.runtime.registerResourceModule("oci", "database/exadataIormConfig", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalContainerDatabase", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalContainerDatabaseManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalDatabaseConnector", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalNonContainerDatabase", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalNonContainerDatabaseManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalNonContainerDatabaseOperationsInsightsManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalPluggableDatabase", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalPluggableDatabaseManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/externalPluggableDatabaseOperationsInsightsManagement", _module)
pulumi.runtime.registerResourceModule("oci", "database/keyStore", _module)
pulumi.runtime.registerResourceModule("oci", "database/maintenanceRun", _module)
pulumi.runtime.registerResourceModule("oci", "database/migration", _module)
pulumi.runtime.registerResourceModule("oci", "database/pluggableDatabase", _module)
pulumi.runtime.registerResourceModule("oci", "database/pluggableDatabasesLocalClone", _module)
pulumi.runtime.registerResourceModule("oci", "database/pluggableDatabasesRemoteClone", _module)
pulumi.runtime.registerResourceModule("oci", "database/vmCluster", _module)
pulumi.runtime.registerResourceModule("oci", "database/vmClusterNetwork", _module)
