// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Inputs
{

    public sealed class ApigatewayDeploymentSpecificationRouteRequestPoliciesHeaderValidationsArgs : Pulumi.ResourceArgs
    {
        [Input("headers")]
        private InputList<Inputs.ApigatewayDeploymentSpecificationRouteRequestPoliciesHeaderValidationsHeaderArgs>? _headers;

        /// <summary>
        /// (Updatable)
        /// </summary>
        public InputList<Inputs.ApigatewayDeploymentSpecificationRouteRequestPoliciesHeaderValidationsHeaderArgs> Headers
        {
            get => _headers ?? (_headers = new InputList<Inputs.ApigatewayDeploymentSpecificationRouteRequestPoliciesHeaderValidationsHeaderArgs>());
            set => _headers = value;
        }

        /// <summary>
        /// (Updatable) Validation behavior mode.
        /// </summary>
        [Input("validationMode")]
        public Input<string>? ValidationMode { get; set; }

        public ApigatewayDeploymentSpecificationRouteRequestPoliciesHeaderValidationsArgs()
        {
        }
    }
}
