// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Inputs
{

    public sealed class DevopsDeploymentDeployPipelineEnvironmentsItemDeployPipelineStagesGetArgs : Pulumi.ResourceArgs
    {
        [Input("items")]
        private InputList<Inputs.DevopsDeploymentDeployPipelineEnvironmentsItemDeployPipelineStagesItemGetArgs>? _items;

        /// <summary>
        /// List of arguments provided at the time of deployment.
        /// </summary>
        public InputList<Inputs.DevopsDeploymentDeployPipelineEnvironmentsItemDeployPipelineStagesItemGetArgs> Items
        {
            get => _items ?? (_items = new InputList<Inputs.DevopsDeploymentDeployPipelineEnvironmentsItemDeployPipelineStagesItemGetArgs>());
            set => _items = value;
        }

        public DevopsDeploymentDeployPipelineEnvironmentsItemDeployPipelineStagesGetArgs()
        {
        }
    }
}
