// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * This data source provides the list of Limit Definitions in Oracle Cloud Infrastructure Limits service.
 *
 * Includes a list of resource limits that are currently supported.
 * If the 'areQuotasSupported' property is true, you can create quota policies on top of this limit at the
 * compartment level.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testLimitDefinitions = oci.GetLimitsLimitDefinitions({
 *     compartmentId: _var.tenancy_ocid,
 *     name: _var.limit_definition_name,
 *     serviceName: oci_limits_service.test_service.name,
 * });
 * ```
 */
export function getLimitsLimitDefinitions(args: GetLimitsLimitDefinitionsArgs, opts?: pulumi.InvokeOptions): Promise<GetLimitsLimitDefinitionsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("oci:index/getLimitsLimitDefinitions:GetLimitsLimitDefinitions", {
        "compartmentId": args.compartmentId,
        "filters": args.filters,
        "name": args.name,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking GetLimitsLimitDefinitions.
 */
export interface GetLimitsLimitDefinitionsArgs {
    /**
     * The OCID of the parent compartment (remember that the tenancy is simply the root compartment).
     */
    compartmentId: string;
    filters?: inputs.GetLimitsLimitDefinitionsFilter[];
    /**
     * Optional field, filter for a specific resource limit.
     */
    name?: string;
    /**
     * The target service name.
     */
    serviceName?: string;
}

/**
 * A collection of values returned by GetLimitsLimitDefinitions.
 */
export interface GetLimitsLimitDefinitionsResult {
    readonly compartmentId: string;
    readonly filters?: outputs.GetLimitsLimitDefinitionsFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The list of limit_definitions.
     */
    readonly limitDefinitions: outputs.GetLimitsLimitDefinitionsLimitDefinition[];
    /**
     * The resource limit name. To be used for writing policies (in case of quotas) or other programmatic calls.
     */
    readonly name?: string;
    /**
     * The service name of the limit.
     */
    readonly serviceName?: string;
}
