// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * This data source provides the list of Channels in Oracle Cloud Infrastructure MySQL Database service.
 *
 * Lists all the Channels that match the specified filters.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testChannels = oci.GetMysqlChannels({
 *     compartmentId: _var.compartment_id,
 *     channelId: oci_mysql_channel.test_channel.id,
 *     dbSystemId: oci_database_db_system.test_db_system.id,
 *     displayName: _var.channel_display_name,
 *     isEnabled: _var.channel_is_enabled,
 *     state: _var.channel_state,
 * });
 * ```
 */
export function getMysqlChannels(args: GetMysqlChannelsArgs, opts?: pulumi.InvokeOptions): Promise<GetMysqlChannelsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("oci:index/getMysqlChannels:GetMysqlChannels", {
        "channelId": args.channelId,
        "compartmentId": args.compartmentId,
        "dbSystemId": args.dbSystemId,
        "displayName": args.displayName,
        "filters": args.filters,
        "isEnabled": args.isEnabled,
        "state": args.state,
    }, opts);
}

/**
 * A collection of arguments for invoking GetMysqlChannels.
 */
export interface GetMysqlChannelsArgs {
    /**
     * The OCID of the Channel.
     */
    channelId?: string;
    /**
     * The compartment [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
     */
    compartmentId: string;
    /**
     * The DB System [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
     */
    dbSystemId?: string;
    /**
     * A filter to return only the resource matching the given display name exactly.
     */
    displayName?: string;
    filters?: inputs.GetMysqlChannelsFilter[];
    /**
     * If true, returns only Channels that are enabled. If false, returns only Channels that are disabled.
     */
    isEnabled?: boolean;
    /**
     * The LifecycleState of the Channel.
     */
    state?: string;
}

/**
 * A collection of values returned by GetMysqlChannels.
 */
export interface GetMysqlChannelsResult {
    readonly channelId?: string;
    /**
     * The list of channels.
     */
    readonly channels: outputs.GetMysqlChannelsChannel[];
    /**
     * The OCID of the compartment.
     */
    readonly compartmentId: string;
    /**
     * The OCID of the source DB System.
     */
    readonly dbSystemId?: string;
    /**
     * The user-friendly name for the Channel. It does not have to be unique.
     */
    readonly displayName?: string;
    readonly filters?: outputs.GetMysqlChannelsFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Whether the Channel has been enabled by the user.
     */
    readonly isEnabled?: boolean;
    /**
     * The state of the Channel.
     */
    readonly state?: string;
}
