// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * This data source provides the list of Publication Packages in Oracle Cloud Infrastructure Marketplace service.
 *
 * Lists the packages in the given Publication
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testPublicationPackages = oci.GetMarketplacePublicationPackages({
 *     publicationId: oci_marketplace_publication.test_publication.id,
 *     packageType: _var.publication_package_package_type,
 *     packageVersion: _var.publication_package_package_version,
 * });
 * ```
 */
export function getMarketplacePublicationPackages(args: GetMarketplacePublicationPackagesArgs, opts?: pulumi.InvokeOptions): Promise<GetMarketplacePublicationPackagesResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("oci:index/getMarketplacePublicationPackages:GetMarketplacePublicationPackages", {
        "filters": args.filters,
        "packageType": args.packageType,
        "packageVersion": args.packageVersion,
        "publicationId": args.publicationId,
    }, opts);
}

/**
 * A collection of arguments for invoking GetMarketplacePublicationPackages.
 */
export interface GetMarketplacePublicationPackagesArgs {
    filters?: inputs.GetMarketplacePublicationPackagesFilter[];
    /**
     * A filter to return only packages that match the given package type exactly.
     */
    packageType?: string;
    /**
     * The version of the package. Package versions are unique within a listing.
     */
    packageVersion?: string;
    /**
     * The unique identifier for the listing.
     */
    publicationId: string;
}

/**
 * A collection of values returned by GetMarketplacePublicationPackages.
 */
export interface GetMarketplacePublicationPackagesResult {
    readonly filters?: outputs.GetMarketplacePublicationPackagesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The specified package's type.
     */
    readonly packageType?: string;
    readonly packageVersion?: string;
    readonly publicationId: string;
    /**
     * The list of publication_packages.
     */
    readonly publicationPackages: outputs.GetMarketplacePublicationPackagesPublicationPackage[];
}
