// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * This data source provides details about a specific Backend Health resource in Oracle Cloud Infrastructure Network Load Balancer service.
 *
 * Retrieves the current health status of the specified backend server.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testBackendHealth = oci.GetNetworkLoadBalancerBackendHealth({
 *     backendName: oci_network_load_balancer_backend.test_backend.name,
 *     backendSetName: oci_network_load_balancer_backend_set.test_backend_set.name,
 *     networkLoadBalancerId: oci_network_load_balancer_network_load_balancer.test_network_load_balancer.id,
 * });
 * ```
 */
export function getNetworkLoadBalancerBackendHealth(args: GetNetworkLoadBalancerBackendHealthArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkLoadBalancerBackendHealthResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("oci:index/getNetworkLoadBalancerBackendHealth:GetNetworkLoadBalancerBackendHealth", {
        "backendName": args.backendName,
        "backendSetName": args.backendSetName,
        "networkLoadBalancerId": args.networkLoadBalancerId,
    }, opts);
}

/**
 * A collection of arguments for invoking GetNetworkLoadBalancerBackendHealth.
 */
export interface GetNetworkLoadBalancerBackendHealthArgs {
    /**
     * The name of the backend server for which to retrieve the health status, specified as <ip>:<port> or as <ip> <OCID>:<port>.  Example: `10.0.0.3:8080` or `ocid1.privateip..oc1.<var>&lt;unique_ID&gt;</var>:8080`
     */
    backendName: string;
    /**
     * The name of the backend set associated with the backend server for which to retrieve the health status.  Example: `exampleBackendSet`
     */
    backendSetName: string;
    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the network load balancer to update.
     */
    networkLoadBalancerId: string;
}

/**
 * A collection of values returned by GetNetworkLoadBalancerBackendHealth.
 */
export interface GetNetworkLoadBalancerBackendHealthResult {
    readonly backendName: string;
    readonly backendSetName: string;
    /**
     * A list of the most recent health check results returned for the specified backend server.
     */
    readonly healthCheckResults: outputs.GetNetworkLoadBalancerBackendHealthHealthCheckResult[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly networkLoadBalancerId: string;
    /**
     * The general health status of the specified backend server.
     * *   **OK:**  All health check probes return `OK`
     * *   **WARNING:** At least one of the health check probes does not return `OK`
     * *   **CRITICAL:** None of the health check probes return `OK`. *
     * *   **UNKNOWN:** One of the health checks probes return `UNKNOWN`,
     * *   or the system is unable to retrieve metrics at this time.
     */
    readonly status: string;
}
